#!/usr/bin/env python3
"""
Generalized Neural Network Poisson Algebra Engine
===================================================

Computes the Lie algebra generated by pairwise Hamiltonians of
neural network training dynamics for arbitrary:

  - n_layers (L): number of scalar weight layers (L >= 2)
  - width (k): weight dimension per layer (k=1 scalar, k>1 vector)
  - coupling_type: gradient-product, hessian, symmetric, fisher
  - loss_function: mse, cross_entropy, l1
  - activation: linear, relu_taylor, tanh_taylor

Phase space is 2*L*k dimensional for width-k networks.
For k=1, each weight w_i is a scalar with conjugate momentum v_i.

Usage
-----
    python nn_algebra.py --n-layers 3 --coupling gradient
    python nn_algebra.py --n-layers 4 --coupling gradient --max-level 2
    python nn_algebra.py --sweep depth     # L=2..5, gradient coupling
    python nn_algebra.py --sweep coupling  # all couplings, L=3
    python nn_algebra.py --sweep full      # all combinations
"""

import os
import sys
import json
import argparse
import numpy as np
from time import time
from itertools import combinations

import sympy as sp
from sympy import (symbols, diff, Integer, cancel, expand, Add,
                   Rational, Symbol, Abs)

os.environ["PYTHONUNBUFFERED"] = "1"
sys.setrecursionlimit(500000)


# =====================================================================
# Dynamic phase-space construction
# =====================================================================
def build_phase_space(n_layers, width=1):
    """
    Build symbolic phase-space variables for an L-layer, width-k network.

    Returns:
        weights: list of symbols [w_1, ..., w_L] (or w_i_j for width>1)
        momenta: list of symbols [v_1, ..., v_L]
        q_vars: flat list of all position symbols
        p_vars: flat list of all momentum symbols
    """
    weights = []
    momenta = []
    q_vars = []
    p_vars = []

    if width == 1:
        for i in range(1, n_layers + 1):
            w = Symbol(f"w{i}", real=True)
            v = Symbol(f"v{i}", real=True)
            weights.append(w)
            momenta.append(v)
            q_vars.append(w)
            p_vars.append(v)
    else:
        for i in range(1, n_layers + 1):
            layer_w = []
            layer_v = []
            for j in range(1, width + 1):
                w = Symbol(f"w{i}_{j}", real=True)
                v = Symbol(f"v{i}_{j}", real=True)
                layer_w.append(w)
                layer_v.append(v)
                q_vars.append(w)
                p_vars.append(v)
            weights.append(layer_w)
            momenta.append(layer_v)

    return weights, momenta, q_vars, p_vars


def poisson_bracket_generic(f, g, q_vars, p_vars):
    """
    Generic Poisson bracket for polynomial expressions.
    No chain rule needed since NN losses are polynomial in weights.

    {f, g} = sum_i (df/dq_i * dg/dp_i - df/dp_i * dg/dq_i)
    """
    result = Integer(0)
    for q, p in zip(q_vars, p_vars):
        result += diff(f, q) * diff(g, p) - diff(f, p) * diff(g, q)
    return result


def simplify_gen(expr):
    """Light simplification for polynomial expressions."""
    return cancel(expr)


# =====================================================================
# Loss function builders
# =====================================================================
def build_loss_mse(weights, width=1):
    """
    MSE loss for a linear network: L = (w_L * ... * w_1 * x - t)^2 / 2
    With x=1, t=1: L = (prod(w_i) - 1)^2 / 2
    """
    if width == 1:
        product = Integer(1)
        for w in weights:
            product *= w
        return (product - 1)**2 / 2, product
    else:
        product = weights[0][0]
        for layer in weights[1:]:
            product *= layer[0]
        return (product - 1)**2 / 2, product


def build_loss_l1(weights, width=1):
    """
    L1 loss approximated via smooth abs: L = |prod(w_i) - 1|
    We use a polynomial Taylor approximation: |z| ≈ sqrt(z^2 + eps)
    For exact polynomial algebra, use z^2 as proxy (same algebra structure).
    """
    if width == 1:
        product = Integer(1)
        for w in weights:
            product *= w
    else:
        product = weights[0][0]
        for layer in weights[1:]:
            product *= layer[0]
    z = product - 1
    return z**2, product


def build_loss_cross_entropy(weights, width=1):
    """
    Cross-entropy approximation for linear networks.
    CE = -log(sigma(f(x))) where sigma is sigmoid.
    Taylor expand: -log(sigmoid(z)) ≈ z^2/4 + z^4/48 + ... for small z.
    We use the leading quadratic + quartic terms.
    """
    if width == 1:
        product = Integer(1)
        for w in weights:
            product *= w
    else:
        product = weights[0][0]
        for layer in weights[1:]:
            product *= layer[0]
    z = product - 1
    return z**2 / 4 + z**4 / 48, product


# =====================================================================
# Coupling type builders
# =====================================================================
def build_couplings(weights, momenta, loss_func, width=1,
                    coupling_type="gradient", n_layers=None):
    """
    Build pairwise Hamiltonians H_ij for all pairs (i,j).

    Returns dict of {(i,j): H_ij} where i < j (0-indexed layer pairs).
    """
    if n_layers is None:
        n_layers = len(weights)

    L, product = loss_func(weights, width)

    if width == 1:
        gradients = [diff(L, w) for w in weights]
    else:
        gradients = [diff(L, w[0]) for w in weights]

    hamiltonians = {}

    for i, j in combinations(range(n_layers), 2):
        if width == 1:
            T_i = momenta[i]**2 / 2
            T_j = momenta[j]**2 / 2
        else:
            T_i = sum(v**2 for v in momenta[i]) / 2
            T_j = sum(v**2 for v in momenta[j]) / 2

        if coupling_type == "gradient":
            V_ij = gradients[i] * gradients[j] / 2

        elif coupling_type == "hessian":
            if width == 1:
                d2L = diff(gradients[i], weights[j])
                V_ij = d2L * weights[i] * weights[j] / 2
            else:
                d2L = diff(gradients[i], weights[j][0])
                V_ij = d2L * weights[i][0] * weights[j][0] / 2

        elif coupling_type == "symmetric":
            V_ij = L / sp.binomial(n_layers, 2)

        elif coupling_type == "fisher":
            V_ij = gradients[i] * gradients[j] * (1 - L)

        elif coupling_type == "gradient_sum":
            V_ij = (gradients[i]**2 + gradients[j]**2) / 2

        elif coupling_type == "gradient_abs":
            V_ij = (gradients[i] + gradients[j])**2 / 2

        elif coupling_type == "hessian_plain":
            if width == 1:
                d2L = diff(gradients[i], weights[j])
                V_ij = d2L / 2
            else:
                d2L = diff(gradients[i], weights[j][0])
                V_ij = d2L / 2

        elif coupling_type == "hessian_full":
            if width == 1:
                hii = diff(gradients[i], weights[i])
                hjj = diff(gradients[j], weights[j])
                hij = diff(gradients[i], weights[j])
                V_ij = (hii * weights[i]**2 + hjj * weights[j]**2
                        + 2 * hij * weights[i] * weights[j]) / 2
            else:
                hii = diff(gradients[i], weights[i][0])
                hjj = diff(gradients[j], weights[j][0])
                hij = diff(gradients[i], weights[j][0])
                V_ij = (hii * weights[i][0]**2 + hjj * weights[j][0]**2
                        + 2 * hij * weights[i][0] * weights[j][0]) / 2

        elif coupling_type == "directional":
            V_ij = gradients[i] * momenta[i] + gradients[j] * momenta[j] \
                if width == 1 else \
                gradients[i] * momenta[i][0] + gradients[j] * momenta[j][0]

        elif coupling_type == "natural_gradient":
            V_ij = gradients[i] * gradients[j] * (1 + L / 2)

        elif coupling_type == "loss_power":
            V_ij = L**2 / sp.binomial(n_layers, 2)

        elif coupling_type == "gradient_cubic":
            V_ij = gradients[i]**2 * gradients[j] + gradients[i] * gradients[j]**2

        else:
            raise ValueError(f"Unknown coupling type: {coupling_type}")

        hamiltonians[(i, j)] = expand(T_i + T_j + V_ij)

    return hamiltonians


# =====================================================================
# Activation support (Taylor expansion approach)
# =====================================================================
def build_loss_with_activation(weights, activation="linear",
                               taylor_order=3, width=1):
    """
    Build loss with nonlinear activation applied between layers.

    For activation='linear': standard product
    For activation='tanh_taylor': tanh(z) ≈ z - z^3/3 (order-3 Taylor)
    For activation='relu_taylor': ReLU ≈ z/2 + z^2/4 (smooth approx)

    Uses minimal Taylor order to keep polynomial degree manageable.
    """
    if activation == "linear":
        return build_loss_mse(weights, width)

    if width == 1:
        z = weights[0]
        for w in weights[1:]:
            if activation == "tanh_taylor":
                z = z - z**3 / 3
            elif activation == "relu_taylor":
                z = z / 2 + z**2 / 4
            z = w * z
    else:
        z = weights[0][0]
        for w in weights[1:]:
            if activation == "tanh_taylor":
                z = z - z**3 / 3
            elif activation == "relu_taylor":
                z = z / 2 + z**2 / 4
            z = w[0] * z

    loss = expand((z - 1)**2 / 2)
    return loss, z


# =====================================================================
# SVD gap analysis (self-contained)
# =====================================================================
def svd_gap_analysis(eval_matrix, label=""):
    """Compute SVD, find gaps, return rank."""
    norms = np.linalg.norm(eval_matrix, axis=0)
    norms[norms < 1e-15] = 1.0
    M = eval_matrix / norms

    U, s, Vt = np.linalg.svd(M, full_matrices=False)

    noise_threshold = 1e-8 * s[0]
    n_meaningful = int(np.sum(s > noise_threshold))

    best_gap_ratio = 1.0
    best_gap_idx = -1
    for i in range(min(n_meaningful, len(s) - 1)):
        if s[i + 1] > noise_threshold:
            gap = s[i] / s[i + 1]
        else:
            gap = s[i] / max(s[i + 1], 1e-300)
        if gap > best_gap_ratio and i >= 1:
            best_gap_ratio = gap
            best_gap_idx = i

    if best_gap_ratio > 1e4:
        rank = best_gap_idx + 1
    elif best_gap_ratio > 10:
        rank = best_gap_idx + 1
    else:
        rank = n_meaningful

    return rank, s


# =====================================================================
# Phase-space sampling
# =====================================================================
def sample_phase_space_nn(n_dims, n_samples, seed=42, w_range=3.0, v_range=1.0):
    """
    Sample phase-space points for a system with n_dims total
    (n_dims/2 positions + n_dims/2 momenta).
    """
    rng = np.random.RandomState(seed)
    n_q = n_dims // 2
    Z = np.zeros((n_samples, n_dims))
    Z[:, :n_q] = rng.uniform(-w_range, w_range, (n_samples, n_q))
    Z[:, n_q:] = rng.uniform(-v_range, v_range, (n_samples, n_q))
    return Z


def _make_flat_func(expr, all_vars, label="_f"):
    """Build a flat function via temp file to bypass compiler recursion."""
    import tempfile
    import importlib.util
    from sympy import pycode

    var_names = [str(v) for v in all_vars]
    sig = ", ".join(var_names)

    terms = sp.Add.make_args(expr)
    lines = [
        "import numpy as _np",
        "from numpy import exp, log, sqrt, sin, cos, abs, power",
        f"def {label}({sig}):",
    ]
    max_chunk = 50
    if len(terms) <= max_chunk:
        lines.append(f"    _result = {pycode(expr)}")
    else:
        lines.append("    _result = 0")
        for i in range(0, len(terms), max_chunk):
            chunk = sp.Add(*terms[i:i + max_chunk])
            lines.append(f"    _result += {pycode(chunk)}")
    lines.append("    return _result")

    code = "\n".join(lines)
    tmp = tempfile.NamedTemporaryFile(
        mode="w", suffix=".py", delete=False, prefix="flat_")
    tmp.write(code)
    tmp.flush()
    tmp.close()

    spec = importlib.util.spec_from_file_location(f"_flat_{label}", tmp.name)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return getattr(mod, label)


def lambdify_exprs(exprs, all_vars):
    """Convert SymPy expressions to fast numpy callables."""
    n = len(exprs)
    funcs = []
    for idx, expr in enumerate(exprs):
        try:
            f = sp.lambdify(all_vars, expr, modules="numpy", cse=False)
            funcs.append(f)
        except (RecursionError, Exception):
            try:
                f = _make_flat_func(expr, all_vars, label=f"g{idx}")
                funcs.append(f)
            except (RecursionError, Exception):
                f = sp.lambdify(all_vars, expr, modules="numpy", cse=True)
                funcs.append(f)

    def evaluate(Z):
        args = [Z[:, i] for i in range(Z.shape[1])]
        n_pts = Z.shape[0]
        cols = []
        for f in funcs:
            val = f(*args)
            arr = np.atleast_1d(np.asarray(val, dtype=float)).ravel()
            if arr.shape[0] == 1:
                arr = np.full(n_pts, arr[0])
            cols.append(arr[:n_pts])
        return np.column_stack(cols)

    return evaluate


# =====================================================================
# Core computation
# =====================================================================
def compute_nn_algebra(n_layers=3, width=1, coupling_type="gradient",
                       loss_fn="mse", activation="linear",
                       max_level=3, n_samples=500, seed=42,
                       verbose=True):
    """
    Compute the Poisson bracket Lie algebra for a neural network.

    Returns a result dict with dimension sequence and metadata.
    """
    t_start = time()

    weights, momenta, q_vars, p_vars = build_phase_space(n_layers, width)
    all_vars = q_vars + p_vars
    n_dims = len(all_vars)
    n_pairs = n_layers * (n_layers - 1) // 2

    if verbose:
        print("=" * 70)
        print(f"NEURAL NETWORK POISSON ALGEBRA")
        print(f"  Layers: {n_layers}, Width: {width}, "
              f"Phase space: {n_dims}D")
        print(f"  Coupling: {coupling_type}, Loss: {loss_fn}, "
              f"Activation: {activation}")
        print(f"  Max level: {max_level}, Samples: {n_samples}")
        print("=" * 70)

    if activation != "linear":
        loss_builder = lambda w, k: build_loss_with_activation(
            w, activation=activation, width=k)
    elif loss_fn == "mse":
        loss_builder = build_loss_mse
    elif loss_fn == "l1":
        loss_builder = build_loss_l1
    elif loss_fn == "cross_entropy":
        loss_builder = build_loss_cross_entropy
    else:
        raise ValueError(f"Unknown loss function: {loss_fn}")

    hamiltonians = build_couplings(
        weights, momenta, loss_builder,
        width=width, coupling_type=coupling_type, n_layers=n_layers
    )

    pair_keys = sorted(hamiltonians.keys())
    all_exprs = []
    all_names = []
    all_levels = []
    computed_pairs = set()

    if verbose:
        print(f"\n--- Level 0: {n_pairs} Pairwise Hamiltonians ---")
    for idx, (i, j) in enumerate(pair_keys):
        expr = hamiltonians[(i, j)]
        name = f"H{i+1}{j+1}"
        all_exprs.append(expr)
        all_names.append(name)
        all_levels.append(0)
        nterms = len(Add.make_args(expr))
        if verbose:
            print(f"  {name}: {nterms} terms")

    for i in range(n_pairs):
        for j in range(i + 1, n_pairs):
            computed_pairs.add(frozenset({i, j}))

    # Level 1
    if max_level >= 1:
        if verbose:
            print(f"\n--- Level 1 ---")
        t_lv = time()
        new_exprs = []
        new_names = []
        n_cand = 0
        for i in range(n_pairs):
            for j in range(i + 1, n_pairs):
                n_cand += 1
                t0 = time()
                expr = poisson_bracket_generic(
                    all_exprs[i], all_exprs[j], q_vars, p_vars)
                expr = simplify_gen(expr)
                nterms = len(Add.make_args(expr))
                if verbose:
                    print(f"  [{n_cand}] {{{all_names[i]},{all_names[j]}}} "
                          f"-> {nterms} terms [{time()-t0:.1f}s]")
                new_exprs.append(expr)
                bname = f"{{{all_names[i]},{all_names[j]}}}"
                new_names.append(bname)

        for expr, name in zip(new_exprs, new_names):
            all_exprs.append(expr)
            all_names.append(name)
            all_levels.append(1)

        if verbose:
            n_zero = sum(1 for e in new_exprs if e == 0)
            print(f"  Level 1: {len(new_exprs)} candidates "
                  f"({n_zero} zero) [{time()-t_lv:.1f}s]")

    # Levels 2+
    for level in range(2, max_level + 1):
        if verbose:
            print(f"\n--- Level {level} ---")
        t_lv = time()

        frontier = [i for i, lv in enumerate(all_levels) if lv == level - 1]
        n_existing = len(all_exprs)
        new_exprs = []
        new_names = []
        n_cand = 0

        for i in frontier:
            for j in range(n_existing):
                if i == j:
                    continue
                pair = frozenset({i, j})
                if pair in computed_pairs:
                    continue
                computed_pairs.add(pair)
                if all_exprs[i] == 0 or all_exprs[j] == 0:
                    continue

                n_cand += 1
                t0 = time()
                expr = poisson_bracket_generic(
                    all_exprs[i], all_exprs[j], q_vars, p_vars)
                t_b = time() - t0
                t0s = time()
                expr = simplify_gen(expr)
                t_s = time() - t0s
                nterms = len(Add.make_args(expr))

                if verbose and (n_cand <= 20 or n_cand % 50 == 0):
                    print(f"  [{n_cand:>4d}] {{{all_names[i]},{all_names[j]}}} "
                          f"bracket {t_b:.1f}s simplify {t_s:.1f}s "
                          f"-> {nterms} terms")

                new_exprs.append(expr)
                new_names.append(f"{{{all_names[i]},{all_names[j]}}}")

        for expr, name in zip(new_exprs, new_names):
            all_exprs.append(expr)
            all_names.append(name)
            all_levels.append(level)

        if verbose:
            n_zero = sum(1 for e in new_exprs if e == 0)
            print(f"  Level {level}: {len(new_exprs)} candidates "
                  f"({n_zero} zero) [{time()-t_lv:.1f}s]")

    # SVD analysis
    nonzero_mask = [i for i, e in enumerate(all_exprs) if e != 0]
    nonzero_exprs = [all_exprs[i] for i in nonzero_mask]
    nonzero_levels = [all_levels[i] for i in nonzero_mask]

    if verbose:
        print(f"\n--- SVD Analysis ---")
        print(f"  Total generators: {len(all_exprs)} "
              f"(non-zero: {len(nonzero_exprs)})")

    if len(nonzero_exprs) == 0:
        dims = [n_pairs] + [n_pairs] * max_level
        return _build_result(dims, n_layers, width, coupling_type,
                             loss_fn, activation, max_level,
                             len(all_exprs), time() - t_start)

    Z = sample_phase_space_nn(n_dims, n_samples, seed)
    evaluate = lambdify_exprs(nonzero_exprs, all_vars)
    eval_matrix = evaluate(Z)

    if verbose:
        print(f"  Eval matrix: {eval_matrix.shape}")

    level_dims = {}
    for lv in range(max_level + 1):
        mask = [i for i, l in enumerate(nonzero_levels) if l <= lv]
        if not mask:
            level_dims[lv] = 0
            continue
        sub = eval_matrix[:, mask]
        rank, _ = svd_gap_analysis(sub, label=f"level {lv}")
        level_dims[lv] = rank
        if verbose:
            print(f"  Dim through level {lv}: {rank}")

    dims = [level_dims[lv] for lv in range(max_level + 1)]
    new_per_level = [dims[0]]
    for i in range(1, len(dims)):
        new_per_level.append(dims[i] - dims[i - 1])

    elapsed = time() - t_start

    if verbose:
        print(f"\n  Dimension sequence: {dims}")
        print(f"  New per level: {new_per_level}")
        print(f"  Total time: {elapsed:.1f}s")

    return _build_result(dims, n_layers, width, coupling_type,
                         loss_fn, activation, max_level,
                         len(all_exprs), elapsed)


def _build_result(dims, n_layers, width, coupling_type,
                  loss_fn, activation, max_level, n_generators, elapsed):
    new_per_level = [dims[0]]
    for i in range(1, len(dims)):
        new_per_level.append(dims[i] - dims[i - 1])

    stabilized = False
    for i in range(1, len(dims)):
        if dims[i] == dims[i - 1]:
            stabilized = True
            break

    return {
        "n_layers": n_layers,
        "width": width,
        "coupling_type": coupling_type,
        "loss_function": loss_fn,
        "activation": activation,
        "max_level": max_level,
        "dimension_sequence": dims,
        "new_per_level": new_per_level,
        "n_generators": n_generators,
        "stabilized": stabilized,
        "computation_time_seconds": round(elapsed, 1),
        "computation_method": "numerical_SVD",
    }


def save_result(result, output_dir="results/neural_algebras"):
    """Save result as JSON."""
    os.makedirs(output_dir, exist_ok=True)
    L = result["n_layers"]
    k = result["width"]
    c = result["coupling_type"]
    loss = result["loss_function"]
    act = result["activation"]
    fname = f"nn_L{L}_k{k}_{c}_{loss}_{act}.json"
    path = os.path.join(output_dir, fname)
    with open(path, "w") as f:
        json.dump(result, f, indent=2)
    print(f"  Saved: {path}")
    return path


# =====================================================================
# Sweep runners
# =====================================================================
def run_depth_sweep(max_level=3, n_samples=500):
    """Sweep L=2..5 with gradient coupling."""
    results = []
    for L in [2, 3, 4, 5]:
        print(f"\n{'#' * 70}")
        print(f"# DEPTH SWEEP: L={L}")
        print(f"{'#' * 70}")
        r = compute_nn_algebra(
            n_layers=L, coupling_type="gradient",
            max_level=min(max_level, 3),
            n_samples=n_samples)
        save_result(r)
        results.append(r)
    return results


def run_coupling_sweep(n_layers=3, max_level=3, n_samples=500,
                       couplings=None):
    """Sweep coupling types for fixed L."""
    if couplings is None:
        couplings = ["gradient", "hessian", "symmetric", "fisher"]
    results = []
    for coupling in couplings:
        print(f"\n{'#' * 70}")
        print(f"# COUPLING SWEEP: {coupling}")
        print(f"{'#' * 70}")
        r = compute_nn_algebra(
            n_layers=n_layers, coupling_type=coupling,
            max_level=max_level, n_samples=n_samples)
        save_result(r)
        results.append(r)
    return results


def run_activation_sweep(n_layers=3, max_level=3, n_samples=500):
    """Sweep activations for fixed L."""
    results = []
    for act in ["linear", "tanh_taylor", "relu_taylor"]:
        print(f"\n{'#' * 70}")
        print(f"# ACTIVATION SWEEP: {act}")
        print(f"{'#' * 70}")
        r = compute_nn_algebra(
            n_layers=n_layers, coupling_type="gradient",
            activation=act, max_level=max_level,
            n_samples=n_samples)
        save_result(r)
        results.append(r)
    return results


def run_width_sweep(n_layers=3, max_level=3, n_samples=500):
    """Sweep width k=1,2,3 for fixed L."""
    results = []
    for k in [1, 2, 3]:
        print(f"\n{'#' * 70}")
        print(f"# WIDTH SWEEP: k={k}")
        print(f"{'#' * 70}")
        r = compute_nn_algebra(
            n_layers=n_layers, width=k,
            coupling_type="gradient",
            max_level=max_level, n_samples=n_samples)
        save_result(r)
        results.append(r)
    return results


def run_loss_sweep(n_layers=3, max_level=3, n_samples=500):
    """Sweep loss functions for fixed L."""
    results = []
    for loss in ["mse", "cross_entropy", "l1"]:
        print(f"\n{'#' * 70}")
        print(f"# LOSS SWEEP: {loss}")
        print(f"{'#' * 70}")
        r = compute_nn_algebra(
            n_layers=n_layers, coupling_type="gradient",
            loss_fn=loss, max_level=max_level,
            n_samples=n_samples)
        save_result(r)
        results.append(r)
    return results


def run_full_sweep(max_level=3, n_samples=500):
    """Run all sweep types and print summary table."""
    all_results = []

    print("\n" + "=" * 70)
    print("FULL NEURAL NETWORK ALGEBRA SWEEP")
    print("=" * 70)

    all_results.extend(run_depth_sweep(max_level, n_samples))
    all_results.extend(run_coupling_sweep(3, max_level, n_samples))
    all_results.extend(run_activation_sweep(3, max_level, n_samples))
    all_results.extend(run_width_sweep(3, max_level, n_samples))
    all_results.extend(run_loss_sweep(3, max_level, n_samples))

    print_summary_table(all_results)
    return all_results


def print_summary_table(results):
    """Print a formatted comparison table."""
    print(f"\n{'=' * 90}")
    print("NEURAL NETWORK ALGEBRA SUMMARY")
    print(f"{'=' * 90}")
    print(f"  {'Config':<45s} {'Dims':<25s} {'Match 116?':<12s} Status")
    print(f"  {'-' * 88}")

    for r in results:
        L = r["n_layers"]
        k = r["width"]
        c = r["coupling_type"]
        loss = r["loss_function"]
        act = r["activation"]
        dims = r["dimension_sequence"]
        config = f"L={L} k={k} {c} {loss} {act}"

        dims_str = str(dims)
        if len(dims) >= 4 and dims[3] == 116:
            match = "YES"
        elif len(dims) >= 4:
            match = f"NO ({dims[3]})"
        else:
            match = "N/A"

        status = "STABLE" if r["stabilized"] else "GROWING"
        print(f"  {config:<45s} {dims_str:<25s} {match:<12s} {status}")

    # Check for universality classes
    seq_groups = {}
    for r in results:
        key = tuple(r["dimension_sequence"])
        if key not in seq_groups:
            seq_groups[key] = []
        config = (f"L={r['n_layers']} k={r['width']} "
                  f"{r['coupling_type']} {r['loss_function']} "
                  f"{r['activation']}")
        seq_groups[key].append(config)

    print(f"\n  UNIVERSALITY CLASSES:")
    for seq, configs in sorted(seq_groups.items()):
        print(f"  {list(seq)}: {len(configs)} configurations")
        for c in configs:
            print(f"    - {c}")


# =====================================================================
# Main
# =====================================================================
def main():
    ap = argparse.ArgumentParser(
        description="Generalized Neural Network Poisson Algebra")
    ap.add_argument("--n-layers", type=int, default=3)
    ap.add_argument("--width", type=int, default=1)
    ap.add_argument("--coupling", type=str, default="gradient",
                    choices=["gradient", "hessian", "symmetric", "fisher",
                             "gradient_sum", "gradient_abs", "hessian_plain",
                             "hessian_full", "directional", "natural_gradient",
                             "loss_power", "gradient_cubic"])
    ap.add_argument("--loss", type=str, default="mse",
                    choices=["mse", "cross_entropy", "l1"])
    ap.add_argument("--activation", type=str, default="linear",
                    choices=["linear", "tanh_taylor", "relu_taylor"])
    ap.add_argument("--max-level", type=int, default=3)
    ap.add_argument("--samples", type=int, default=500)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--sweep", type=str, default=None,
                    choices=["depth", "coupling", "activation",
                             "width", "loss", "full"])
    args = ap.parse_args()

    if args.sweep:
        if args.sweep == "depth":
            run_depth_sweep(args.max_level, args.samples)
        elif args.sweep == "coupling":
            run_coupling_sweep(args.n_layers, args.max_level, args.samples)
        elif args.sweep == "activation":
            run_activation_sweep(args.n_layers, args.max_level, args.samples)
        elif args.sweep == "width":
            run_width_sweep(args.n_layers, args.max_level, args.samples)
        elif args.sweep == "loss":
            run_loss_sweep(args.n_layers, args.max_level, args.samples)
        elif args.sweep == "full":
            run_full_sweep(args.max_level, args.samples)
    else:
        r = compute_nn_algebra(
            n_layers=args.n_layers,
            width=args.width,
            coupling_type=args.coupling,
            loss_fn=args.loss,
            activation=args.activation,
            max_level=args.max_level,
            n_samples=args.samples,
            seed=args.seed,
        )
        save_result(r)


if __name__ == "__main__":
    main()
