#!/usr/bin/env python3
"""
Neural Network Poisson Bracket Algebra
========================================

Computes the Lie algebra generated by pairwise interaction
Hamiltonians of a minimal neural network's training dynamics
under the Poisson bracket. Directly comparable to the 3-body
gravitational result [3, 6, 17, 116].

The physics: a 3-layer linear network f(x) = w3*w2*w1*x trained
with SGD+momentum is a Hamiltonian system:
  - Coordinates: weights (w1, w2, w3)
  - Momenta: velocity buffer (v1, v2, v3)
  - Kinetic energy: T_i = v_i^2 / 2
  - Potential energy: MSE loss L = (w3*w2*w1*x - t)^2 / 2

The loss is polynomial in weights, so no auxiliary variable trick
is needed (analogous to the harmonic r^2 case in gravity).

Phase A: Linear network (polynomial loss, multiple decompositions)
Phase B: Weight-space distance analogies (1/r, r^2 sanity checks)

Usage
-----
    python nn_poisson.py                        # all potentials, level 3
    python nn_poisson.py --potential linear      # single potential
    python nn_poisson.py --max-level 2           # quick test
"""

import os
import sys
import argparse
import numpy as np
from time import time
from sympy import (symbols, diff, Integer, cancel, expand, Add,
                   Rational, Symbol)
import sympy as sp

os.environ["PYTHONUNBUFFERED"] = "1"

# Add parent directory to path for imports
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from exact_growth import (
    x1, y1, x2, y2, x3, y3,
    px1, py1, px2, py2, px3, py3,
    u12, u13, u23,
    Q_VARS, P_VARS, U_VARS, ALL_VARS,
    CHAIN_RULE, total_deriv,
    poisson_bracket, simplify_generator,
    svd_gap_analysis,
    lambdify_generators,
)

# =====================================================================
# Variable mapping: neural network -> gravitational engine
#
# We reuse the planar 3-body phase space (12D + 3 auxiliary).
# Only 3+3 = 6 variables are used; the rest contribute zero.
#
#   w1 -> x1   (weight of layer 1)     v1 -> px1  (momentum of layer 1)
#   w2 -> x2   (weight of layer 2)     v2 -> px2  (momentum of layer 2)
#   w3 -> x3   (weight of layer 3)     v3 -> px3  (momentum of layer 3)
#
# y1,y2,y3 and py1,py2,py3 are unused (never appear in Hamiltonians).
# u12,u13,u23 are unused in polynomial potentials.
# The Poisson bracket sums over all 6 (q,p) pairs but unused ones
# contribute zero — no code changes needed.
# =====================================================================
w1, w2, w3 = x1, x2, x3
v1, v2, v3 = px1, px2, px3

# Kinetic energies (1D per layer, no y-component)
T1_nn = v1**2 / 2
T2_nn = v2**2 / 2
T3_nn = v3**2 / 2

# Training data as symbolic constants
x_data = Symbol("x_data", positive=True)
t_data = Symbol("t_data", real=True)


# =====================================================================
# Phase-space sampler for neural network (no u_ij needed)
# =====================================================================
def sample_nn_phase_space(n, seed=42, w_range=3.0, v_range=1.0):
    """
    Sample phase-space points for the neural network system.

    Returns (Z_qp, Z_u) in the format expected by lambdify_generators:
      Z_qp: (N, 12) — positions and momenta (y-variables are random but
                       don't matter since expressions don't use them)
      Z_u:  (N, 3)  — dummy u values (nonzero to avoid division issues
                       in lambdify, but expressions don't use u_ij)
    """
    rng = np.random.RandomState(seed)
    Z_qp = np.zeros((n, 12))
    # Weights: w1=x1, w2=x2, w3=x3 (columns 0, 2, 4 in exact_growth layout)
    # In exact_growth: Q_VARS = [x1, y1, x2, y2, x3, y3]
    # So x1=col0, y1=col1, x2=col2, y2=col3, x3=col4, y3=col5
    Z_qp[:, 0] = rng.uniform(-w_range, w_range, n)  # w1 = x1
    Z_qp[:, 1] = rng.uniform(-w_range, w_range, n)  # y1 (unused, random)
    Z_qp[:, 2] = rng.uniform(-w_range, w_range, n)  # w2 = x2
    Z_qp[:, 3] = rng.uniform(-w_range, w_range, n)  # y2 (unused, random)
    Z_qp[:, 4] = rng.uniform(-w_range, w_range, n)  # w3 = x3
    Z_qp[:, 5] = rng.uniform(-w_range, w_range, n)  # y3 (unused, random)
    # Momenta: v1=px1, v2=px2, v3=px3 (columns 6, 8, 10)
    # P_VARS = [px1, py1, px2, py2, px3, py3]
    Z_qp[:, 6] = rng.uniform(-v_range, v_range, n)   # v1 = px1
    Z_qp[:, 7] = rng.uniform(-v_range, v_range, n)   # py1 (unused)
    Z_qp[:, 8] = rng.uniform(-v_range, v_range, n)   # v2 = px2
    Z_qp[:, 9] = rng.uniform(-v_range, v_range, n)   # py2 (unused)
    Z_qp[:, 10] = rng.uniform(-v_range, v_range, n)  # v3 = px3
    Z_qp[:, 11] = rng.uniform(-v_range, v_range, n)  # py3 (unused)

    # Dummy u_ij values — expressions don't use them, but lambdify
    # expects 15 arguments. Use positive values to avoid issues.
    Z_u = np.ones((n, 3))

    return Z_qp, Z_u


# =====================================================================
# Potential definitions
# =====================================================================
def build_potentials():
    """Build Hamiltonians for each neural network potential type."""

    potentials = {}

    # -----------------------------------------------------------------
    # Phase A: Linear network with MSE loss
    # -----------------------------------------------------------------
    # Network: f(x) = w3 * w2 * w1 * x
    # Loss: L = (f(x) - t)^2 / 2 = (w3*w2*w1*x - t)^2 / 2
    #
    # For symbolic computation, fix x_data=1, t_data=1 (the algebra
    # doesn't depend on these constants — they just scale the potential).
    #
    # L = (w1*w2*w3 - 1)^2 / 2
    #   = (w1^2*w2^2*w3^2 - 2*w1*w2*w3 + 1) / 2
    #
    # Decomposition into pairwise terms:
    # The loss involves ALL THREE weights simultaneously (w1*w2*w3).
    # There is no natural V_12+V_13+V_23 decomposition.
    # We test TWO decompositions to check invariance.

    product = w1 * w2 * w3  # forward pass (x=1)
    L = (product - 1)**2 / 2

    # --- Decomposition A: Symmetric partition ---
    # Distribute the loss into three equal pairwise shares:
    # H_ij = T_i + T_j + L/3
    # This is the simplest decomposition: each pair "shares" the full
    # loss equally, and each body's kinetic energy appears in two H_ij.
    potentials["linear_symmetric"] = {
        "name": "linear_symmetric",
        "label": "Linear NN (symmetric L/3 partition)",
        "H12": T1_nn + T2_nn + L / 3,
        "H13": T1_nn + T3_nn + L / 3,
        "H23": T2_nn + T3_nn + L / 3,
        "integrable": None,  # unknown
    }

    # --- Decomposition B: Hessian coupling ---
    # V_ij = (d^2 L / dw_i dw_j) * w_i * w_j / 2
    # This captures the "interaction strength" between weights.
    # For L = (w1*w2*w3 - 1)^2 / 2:
    #   d^2L/dw1dw2 = w3^2 * w1*w2*w3^2 + w3*(w1*w2*w3-1)*... (computed below)
    dL_dw1 = diff(L, w1)
    dL_dw2 = diff(L, w2)
    dL_dw3 = diff(L, w3)
    d2L_12 = diff(dL_dw1, w2)
    d2L_13 = diff(dL_dw1, w3)
    d2L_23 = diff(dL_dw2, w3)

    V_12_hess = d2L_12 * w1 * w2 / 2
    V_13_hess = d2L_13 * w1 * w3 / 2
    V_23_hess = d2L_23 * w2 * w3 / 2

    potentials["linear_hessian"] = {
        "name": "linear_hessian",
        "label": "Linear NN (Hessian coupling)",
        "H12": T1_nn + T2_nn + V_12_hess,
        "H13": T1_nn + T3_nn + V_13_hess,
        "H23": T2_nn + T3_nn + V_23_hess,
        "integrable": None,
    }

    # --- Decomposition C: Gradient-product coupling ---
    # V_ij = (dL/dw_i) * (dL/dw_j) / 2
    # Measures how strongly gradient updates for w_i and w_j co-vary.
    # Polynomial for linear networks: (dL/dw1) = (w1w2w3-1)*w2*w3
    V_12_grad = dL_dw1 * dL_dw2 / 2
    V_13_grad = dL_dw1 * dL_dw3 / 2
    V_23_grad = dL_dw2 * dL_dw3 / 2

    potentials["linear_gradient"] = {
        "name": "linear_gradient",
        "label": "Linear NN (gradient-product coupling)",
        "H12": T1_nn + T2_nn + V_12_grad,
        "H13": T1_nn + T3_nn + V_13_grad,
        "H23": T2_nn + T3_nn + V_23_grad,
        "integrable": None,
    }

    # -----------------------------------------------------------------
    # Phase B: Weight-space distance analogies (sanity checks)
    # -----------------------------------------------------------------

    # --- 1D Harmonic: V_ij = (w_i - w_j)^2 ---
    # MUST reproduce the 2D harmonic result or its 1D analog.
    r12_sq = (w1 - w2)**2
    r13_sq = (w1 - w3)**2
    r23_sq = (w2 - w3)**2

    potentials["harmonic_1d"] = {
        "name": "harmonic_1d",
        "label": "1D Harmonic (w_i - w_j)^2 — sanity check",
        "H12": T1_nn + T2_nn + r12_sq,
        "H13": T1_nn + T3_nn + r13_sq,
        "H23": T2_nn + T3_nn + r23_sq,
        "integrable": True,
    }

    # --- 1D Gravity: V_ij = -1/|w_i - w_j| ---
    # Uses u_ij = 1/r_ij auxiliary variables and the existing chain rule.
    # This is the ordinary 1D 3-body problem in weight space.
    # Must match ThreeBodyAlgebra(d_spatial=1) results.
    potentials["gravity_1d"] = {
        "name": "gravity_1d",
        "label": "1D Gravity -1/|w_i-w_j| — must match d=1 3-body",
        "H12": T1_nn + T2_nn - u12,
        "H13": T1_nn + T3_nn - u13,
        "H23": T2_nn + T3_nn - u23,
        "integrable": False,
        "uses_u": True,  # flag: needs proper u_ij sampling
    }

    return potentials


# =====================================================================
# Phase-space sampler that handles both polynomial and u_ij potentials
# =====================================================================
def sample_phase_space(n, seed=42, uses_u=False):
    """
    Sample points appropriate for the potential type.
    For polynomial potentials: u_ij columns are dummy (all ones).
    For 1/r potentials: u_ij = 1/|w_i - w_j| with min separation.
    """
    rng = np.random.RandomState(seed)
    w_range = 3.0
    v_range = 1.0
    min_sep = 0.5

    if not uses_u:
        return sample_nn_phase_space(n, seed, w_range, v_range)

    # For gravity: sample weights with minimum separation, compute u_ij
    Z_qp = np.zeros((n, 12))
    pts = np.empty((0, 12))
    for _ in range(200):
        bs = max((n - pts.shape[0]) * 5, 256)
        b = np.zeros((bs, 12))
        # Only x-variables matter (w1=x1, w2=x2, w3=x3)
        b[:, 0] = rng.uniform(-w_range, w_range, bs)
        b[:, 1] = rng.uniform(-w_range, w_range, bs)  # y1 random
        b[:, 2] = rng.uniform(-w_range, w_range, bs)
        b[:, 3] = rng.uniform(-w_range, w_range, bs)  # y2 random
        b[:, 4] = rng.uniform(-w_range, w_range, bs)
        b[:, 5] = rng.uniform(-w_range, w_range, bs)  # y3 random
        b[:, 6:] = rng.uniform(-v_range, v_range, (bs, 6))

        # Separation in 1D (only x-components matter for u_ij)
        # But the chain rule in exact_growth uses BOTH x and y for u_ij.
        # Since our H only uses u_ij (not y-dependent terms), and the
        # chain rule includes y-contributions, we need r_ij computed
        # from both x and y to match what exact_growth expects.
        dx12 = b[:, 0] - b[:, 2]; dy12 = b[:, 1] - b[:, 3]
        dx13 = b[:, 0] - b[:, 4]; dy13 = b[:, 1] - b[:, 5]
        dx23 = b[:, 2] - b[:, 4]; dy23 = b[:, 3] - b[:, 5]
        ok = ((dx12**2 + dy12**2 > min_sep**2) &
              (dx13**2 + dy13**2 > min_sep**2) &
              (dx23**2 + dy23**2 > min_sep**2))
        pts = np.vstack([pts, b[ok]])
        if pts.shape[0] >= n:
            break
    Z_qp = pts[:n]

    dx12 = Z_qp[:, 0] - Z_qp[:, 2]; dy12 = Z_qp[:, 1] - Z_qp[:, 3]
    dx13 = Z_qp[:, 0] - Z_qp[:, 4]; dy13 = Z_qp[:, 1] - Z_qp[:, 5]
    dx23 = Z_qp[:, 2] - Z_qp[:, 4]; dy23 = Z_qp[:, 3] - Z_qp[:, 5]
    u12_vals = 1.0 / np.sqrt(dx12**2 + dy12**2)
    u13_vals = 1.0 / np.sqrt(dx13**2 + dy13**2)
    u23_vals = 1.0 / np.sqrt(dx23**2 + dy23**2)
    Z_u = np.column_stack([u12_vals, u13_vals, u23_vals])

    return Z_qp, Z_u


# =====================================================================
# Growth computation (generic for any potential)
# =====================================================================
def compute_growth(potential, max_level=3, n_samples=500, seed=42):
    """Run Lie algebra growth for a given Hamiltonian decomposition."""

    H12 = potential["H12"]
    H13 = potential["H13"]
    H23 = potential["H23"]
    uses_u = potential.get("uses_u", False)

    print("=" * 70)
    print(f"POTENTIAL: {potential['label']}")
    integ = potential.get("integrable")
    if integ is True:
        print(f"  Expected: integrable (finite-dim)")
    elif integ is False:
        print(f"  Expected: non-integrable (infinite-dim)")
    else:
        print(f"  Expected: UNKNOWN — this is the experiment!")
    print(f"  Max level: {max_level}, Samples: {n_samples}")
    print("=" * 70)

    # Print Hamiltonians
    print("\n  H12 =", expand(H12))
    print("  H13 =", expand(H13))
    print("  H23 =", expand(H23))

    all_exprs = []
    all_names = []
    all_levels = []
    computed_pairs = set()

    # --- Level 0 ---
    print("\n--- Level 0: Pairwise Hamiltonians ---")
    for name, expr in [("H12", H12), ("H13", H13), ("H23", H23)]:
        all_exprs.append(expr)
        all_names.append(name)
        all_levels.append(0)
        print(f"  {name}: {len(Add.make_args(expr))} terms")

    for i in range(3):
        for j in range(i + 1, 3):
            computed_pairs.add(frozenset({i, j}))

    # --- Level 1 ---
    print("\n--- Level 1: Tidal-competition generators ---")
    pairs_l1 = [
        ("K1", "{H12,H13}", 0, 1),
        ("K2", "{H12,H23}", 0, 2),
        ("K3", "{H13,H23}", 1, 2),
    ]
    for short, full, i, j in pairs_l1:
        print(f"  Computing {full}...", end=" ", flush=True)
        t0 = time()
        expr = poisson_bracket(all_exprs[i], all_exprs[j])
        expr = simplify_generator(expr)
        elapsed = time() - t0
        nterms = len(Add.make_args(expr))
        print(f"{nterms} terms  [{elapsed:.1f}s]")

        if expr == 0:
            print(f"    *** {full} = 0 (Hamiltonians Poisson-commute!) ***")

        all_exprs.append(expr)
        all_names.append(short)
        all_levels.append(1)

    # --- Levels 2+ ---
    for level in range(2, max_level + 1):
        print(f"\n--- Level {level} ---")
        t_level = time()

        frontier_indices = [
            i for i, lv in enumerate(all_levels) if lv == level - 1
        ]
        n_existing = len(all_exprs)

        n_candidates = 0
        new_exprs = []
        new_names = []

        for i in frontier_indices:
            for j in range(n_existing):
                if i == j:
                    continue
                pair = frozenset({i, j})
                if pair in computed_pairs:
                    continue
                computed_pairs.add(pair)

                if all_exprs[i] == 0 or all_exprs[j] == 0:
                    continue

                n_candidates += 1
                ni, nj = all_names[i], all_names[j]
                bracket_name = f"{{{ni},{nj}}}"

                print(f"  [{n_candidates:>4d}] {bracket_name}...",
                      end=" ", flush=True)
                t0 = time()
                expr = poisson_bracket(all_exprs[i], all_exprs[j])
                t_bracket = time() - t0

                t0s = time()
                expr = simplify_generator(expr)
                t_simp = time() - t0s

                nterms = len(Add.make_args(expr))
                print(f"bracket {t_bracket:.1f}s  "
                      f"simplify {t_simp:.1f}s  -> {nterms} terms")

                new_exprs.append(expr)
                new_names.append(bracket_name)

        for expr, name in zip(new_exprs, new_names):
            all_exprs.append(expr)
            all_names.append(name)
            all_levels.append(level)

        elapsed_level = time() - t_level
        n_zero = sum(1 for e in new_exprs if e == 0)
        print(f"\n  Level {level}: {len(new_exprs)} candidates "
              f"({n_zero} zero) in {elapsed_level:.1f}s")

    # --- Jacobi identity check at level 1 ---
    print(f"\n{'=' * 70}")
    print("JACOBI IDENTITY CHECK")
    print(f"{'=' * 70}")
    # {H12, {H13, H23}} + {H13, {H23, H12}} + {H23, {H12, H13}} = 0
    if len(all_exprs) >= 6:
        K1 = all_exprs[3]  # {H12, H13}
        K2 = all_exprs[4]  # {H12, H23}
        K3 = all_exprs[5]  # {H13, H23}
        # Jacobi: {H12, K3} + {H13, {H23, H12}} + {H23, K1} = 0
        # {H23, H12} = -K2, so {H13, -K2} = -{H13, K2}
        J1 = poisson_bracket(H12, K3)
        J2 = poisson_bracket(H13, poisson_bracket(H23, H12))
        J3 = poisson_bracket(H23, K1)
        jacobi = simplify_generator(J1 + J2 + J3)
        if jacobi == 0:
            print("  Jacobi identity: SATISFIED (exact zero)")
        else:
            print(f"  Jacobi identity: VIOLATED! Residual = {jacobi}")
            print("  *** THIS SHOULD NOT HAPPEN — CHECK FORMULATION ***")

    # --- SVD Analysis ---
    nonzero_mask = [i for i, e in enumerate(all_exprs) if e != 0]
    nonzero_exprs = [all_exprs[i] for i in nonzero_mask]
    nonzero_levels = [all_levels[i] for i in nonzero_mask]

    print(f"\n{'=' * 70}")
    print("SVD ANALYSIS")
    print(f"{'=' * 70}")
    print(f"  Total generators: {len(all_exprs)} "
          f"(non-zero: {len(nonzero_exprs)})")

    if len(nonzero_exprs) == 0:
        print("  All expressions are zero — trivial algebra!")
        level_dims = {lv: 0 for lv in range(max_level + 1)}
        level_dims[0] = 3
        return {
            "potential": potential,
            "dims": [level_dims[lv] for lv in range(max_level + 1)],
            "level_dims": level_dims,
            "n_generators": len(all_exprs),
            "stabilised": True,
            "stabilised_at": 0,
        }

    Z_qp, Z_u = sample_phase_space(n_samples, seed, uses_u=uses_u)
    evaluate = lambdify_generators(nonzero_exprs)
    eval_matrix = evaluate(Z_qp, Z_u)
    print(f"  Evaluation matrix shape: {eval_matrix.shape}")

    level_dims = {}
    for lv in range(max_level + 1):
        mask = [i for i, l in enumerate(nonzero_levels) if l <= lv]
        if not mask:
            level_dims[lv] = 0
            print(f"  ==> Dimension through level {lv}: 0")
            continue
        sub = eval_matrix[:, mask]
        rank, svals, _, _ = svd_gap_analysis(
            sub, label=f"(through level {lv})")
        level_dims[lv] = rank
        print(f"  ==> Dimension through level {lv}: {rank}")

    # Check for stabilisation
    dims = [level_dims[lv] for lv in range(max_level + 1)]
    stabilised = False
    stabilised_at = None
    for i in range(1, len(dims)):
        if dims[i] == dims[i - 1]:
            stabilised = True
            stabilised_at = i - 1
            break

    # Summary
    print(f"\n  Potential: {potential['label']}")
    print(f"  Dimension sequence: {dims}")

    new_per_level = [dims[0]]
    for i in range(1, len(dims)):
        new_per_level.append(dims[i] - dims[i - 1])
    print(f"  New-per-level: {new_per_level}")

    if stabilised:
        print(f"  *** STABILISED at level {stabilised_at} "
              f"(dim = {dims[stabilised_at]}) ***")
    else:
        print(f"  *** STILL GROWING at level {max_level} ***")

    return {
        "potential": potential,
        "dims": dims,
        "new_per_level": new_per_level,
        "level_dims": level_dims,
        "n_generators": len(all_exprs),
        "n_nonzero": len(nonzero_exprs),
        "stabilised": stabilised,
        "stabilised_at": stabilised_at,
    }


# =====================================================================
# Main
# =====================================================================
def main():
    ap = argparse.ArgumentParser(
        description="Neural network Poisson bracket algebra"
    )
    ap.add_argument("--max-level", type=int, default=3)
    ap.add_argument("--samples", type=int, default=500)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--potential", type=str, default="all",
                    choices=["all", "linear_symmetric", "linear_hessian",
                             "linear_gradient", "harmonic_1d", "gravity_1d"])
    args = ap.parse_args()

    potentials = build_potentials()

    if args.potential == "all":
        run = potentials
    else:
        run = {args.potential: potentials[args.potential]}

    all_results = {}
    for name, pot in run.items():
        result = compute_growth(
            pot,
            max_level=args.max_level,
            n_samples=args.samples,
            seed=args.seed,
        )
        all_results[name] = result
        print()

    # ---------------------------------------------------------------
    # Comparison table
    # ---------------------------------------------------------------
    if len(all_results) > 1:
        print("\n" + "=" * 70)
        print("NEURAL NETWORK vs GRAVITATIONAL COMPARISON TABLE")
        print("=" * 70)
        print()
        print("  Reference sequences:")
        print("    3-body gravity (2D):  [3, 6, 17, 116]")
        print("    Harmonic (2D):        [3, 6, 13, 15]")
        print("    3-body gravity (1D):  [3, 6, 17, 116]  (spatial dim invariant)")
        print()

        header = f"  {'Potential':<45s}"
        for lv in range(args.max_level + 1):
            header += f"  L{lv:d}"
        header += "  | Status"
        print(header)
        print("  " + "-" * (len(header) + 10))

        for name, result in all_results.items():
            dims = result["dims"]
            row = f"  {result['potential']['label'][:45]:<45s}"
            for d in dims:
                row += f"  {d:>3d}"

            if result["stabilised"]:
                row += (f"  | FINITE (L{result['stabilised_at']}, "
                        f"dim={dims[result['stabilised_at']]})")
            else:
                row += f"  | GROWING"

            print(row)

        # Decomposition invariance check
        print()
        nn_results = {k: v for k, v in all_results.items()
                      if k.startswith("linear_")}
        if len(nn_results) > 1:
            seqs = [tuple(v["dims"]) for v in nn_results.values()]
            if len(set(seqs)) == 1:
                print("  *** DECOMPOSITION INVARIANCE: All neural network ***")
                print("  *** decompositions produce the SAME dimension    ***")
                print("  *** sequence — analogous to mass invariance!     ***")
            else:
                print("  Decomposition-DEPENDENT: different decompositions")
                print("  produce different dimension sequences.")
                print("  The algebra DEPENDS on how the loss is partitioned.")

    # Save results
    os.makedirs(os.path.dirname(__file__) or ".", exist_ok=True)
    outfile = os.path.join(os.path.dirname(__file__), "nn_results.txt")
    with open(outfile, "w") as f:
        f.write("NEURAL NETWORK POISSON BRACKET ALGEBRA RESULTS\n")
        f.write("=" * 50 + "\n\n")
        f.write("Reference: 3-body gravity [3, 6, 17, 116]\n")
        f.write("Reference: Harmonic       [3, 6, 13, 15]\n\n")
        for name, result in all_results.items():
            f.write(f"Potential: {result['potential']['label']}\n")
            f.write(f"  Dimensions: {result['dims']}\n")
            if "new_per_level" in result:
                f.write(f"  New-per-level: {result['new_per_level']}\n")
            f.write(f"  Stabilised: {result['stabilised']}")
            if result["stabilised"]:
                f.write(f" at level {result['stabilised_at']}")
            f.write("\n")
            f.write(f"  Generators: {result['n_generators']}")
            if "n_nonzero" in result:
                f.write(f" (non-zero: {result['n_nonzero']})")
            f.write("\n\n")

    print(f"\n  Results saved to {outfile}")


if __name__ == "__main__":
    main()
