#!/usr/bin/env python3
"""
Three-Body Lie Algebra Growth Characterization
================================================

Numerically determines how the Lie algebra generated by the three
pairwise Hamiltonians of a gravitational three-body system grows
under iterated Poisson brackets.

Key question:  Is the growth polynomial or exponential?
  - Polynomial  ->  residual algebraic structure constrains the chaos
  - Exponential ->  full chaos, complexity multiplies at each level
  - Mass-dependent ->  growth tied to physical configuration

The approach is fully numerical:
  1. Levels 0-1 use analytical formulas (exact).
  2. Levels 2+ use finite differences with adaptive step sizes.
  3. Linear independence is detected via QR projection / SVD at
     many random phase-space sample points.

Usage:
    python algebra_growth.py
    python algebra_growth.py --max-level 5 --samples 300
    python algebra_growth.py --help
"""

import numpy as np
import argparse
import sys
import os
from time import time

# Force unbuffered output so progress is visible in non-interactive shells
os.environ["PYTHONUNBUFFERED"] = "1"

# Try to import matplotlib; plotting is optional
try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    HAS_MPL = True
except ImportError:
    HAS_MPL = False


# =============================================================================
# Constants
# =============================================================================
NDIM = 12  # phase-space dimension (planar 3-body)

# Canonical pairs (q_index, p_index) for the Poisson bracket.
# z = [x1, y1, x2, y2, x3, y3,  px1, py1, px2, py2, px3, py3]
#      0   1   2   3   4   5      6    7    8    9   10   11
CANON_PAIRS = [(0, 6), (1, 7), (2, 8), (3, 9), (4, 10), (5, 11)]

MACHINE_EPS = float(np.finfo(np.float64).eps)  # ~2.2e-16


# =============================================================================
# Phase-space sampling
# =============================================================================
def sample_phase_space(n, seed=42, pos_range=3.0, mom_range=1.0, min_sep=0.5):
    """
    Generate *n* random phase-space points with well-separated bodies.

    Bodies must have pairwise distances > *min_sep* so that the
    gravitational potential stays finite and well-conditioned.
    """
    rng = np.random.RandomState(seed)
    points = np.empty((0, NDIM))
    for _ in range(200):
        batch_size = max((n - points.shape[0]) * 5, 256)
        batch = np.zeros((batch_size, NDIM))
        batch[:, :6] = rng.uniform(-pos_range, pos_range, (batch_size, 6))
        batch[:, 6:] = rng.uniform(-mom_range, mom_range, (batch_size, 6))

        dx12 = batch[:, 0] - batch[:, 2]
        dy12 = batch[:, 1] - batch[:, 3]
        dx13 = batch[:, 0] - batch[:, 4]
        dy13 = batch[:, 1] - batch[:, 5]
        dx23 = batch[:, 2] - batch[:, 4]
        dy23 = batch[:, 3] - batch[:, 5]
        r12 = np.sqrt(dx12**2 + dy12**2)
        r13 = np.sqrt(dx13**2 + dy13**2)
        r23 = np.sqrt(dx23**2 + dy23**2)

        good = (r12 > min_sep) & (r13 > min_sep) & (r23 > min_sep)
        points = np.vstack([points, batch[good]])
        if points.shape[0] >= n:
            break

    if points.shape[0] < n:
        print(f"  Warning: only generated {points.shape[0]}/{n} valid sample points")
    return points[:n]


# =============================================================================
# Analytical generators (levels 0 and 1)
# =============================================================================
class ThreeBodyAlgebra:
    """
    Provides *exact* evaluation functions for the three pairwise
    Hamiltonians (level 0) and their first Poisson brackets — the
    "tidal competition" generators K_i (level 1).

    Having analytical functions for these two levels guarantees that
    the finite-difference computation of levels 2+ starts from an
    accurate foundation.
    """

    def __init__(self, m1=1.0, m2=1.0, m3=1.0, G=1.0):
        self.m1, self.m2, self.m3, self.G = m1, m2, m3, G

    # ----- helpers ----------------------------------------------------------
    def _dists(self, Z):
        """Return displacement components and distances for all pairs."""
        dx12 = Z[:, 0] - Z[:, 2];  dy12 = Z[:, 1] - Z[:, 3]
        dx13 = Z[:, 0] - Z[:, 4];  dy13 = Z[:, 1] - Z[:, 5]
        dx23 = Z[:, 2] - Z[:, 4];  dy23 = Z[:, 3] - Z[:, 5]
        r12 = np.sqrt(dx12**2 + dy12**2)
        r13 = np.sqrt(dx13**2 + dy13**2)
        r23 = np.sqrt(dx23**2 + dy23**2)
        return dx12, dy12, r12, dx13, dy13, r13, dx23, dy23, r23

    # ----- Level 0: pairwise Hamiltonians -----------------------------------
    def H12(self, Z):
        """H_12 = T_1 + T_2 + V_12"""
        px1, py1 = Z[:, 6], Z[:, 7]
        px2, py2 = Z[:, 8], Z[:, 9]
        T = (px1**2 + py1**2) / (2 * self.m1) \
          + (px2**2 + py2**2) / (2 * self.m2)
        dx = Z[:, 0] - Z[:, 2];  dy = Z[:, 1] - Z[:, 3]
        r = np.sqrt(dx**2 + dy**2)
        return T - self.G * self.m1 * self.m2 / r

    def H13(self, Z):
        """H_13 = T_1 + T_3 + V_13"""
        px1, py1 = Z[:, 6], Z[:, 7]
        px3, py3 = Z[:, 10], Z[:, 11]
        T = (px1**2 + py1**2) / (2 * self.m1) \
          + (px3**2 + py3**2) / (2 * self.m3)
        dx = Z[:, 0] - Z[:, 4];  dy = Z[:, 1] - Z[:, 5]
        r = np.sqrt(dx**2 + dy**2)
        return T - self.G * self.m1 * self.m3 / r

    def H23(self, Z):
        """H_23 = T_2 + T_3 + V_23"""
        px2, py2 = Z[:, 8], Z[:, 9]
        px3, py3 = Z[:, 10], Z[:, 11]
        T = (px2**2 + py2**2) / (2 * self.m2) \
          + (px3**2 + py3**2) / (2 * self.m3)
        dx = Z[:, 2] - Z[:, 4];  dy = Z[:, 3] - Z[:, 5]
        r = np.sqrt(dx**2 + dy**2)
        return T - self.G * self.m2 * self.m3 / r

    # ----- Level 1: tidal-competition generators ----------------------------
    # K_i = {H_ab, H_ac} with body i shared between the two pairs.
    # Analytically:  K_i = (1/m_i) * (F_ic - F_ib) . p_i
    # where F_ib is the gravitational force on body i from body b.

    def K1(self, Z):
        """{H12, H13}: tidal competition at body 1."""
        px1, py1 = Z[:, 6], Z[:, 7]
        dx12, dy12, r12, dx13, dy13, r13, _, _, _ = self._dists(Z)
        # (x3-x1) = -dx13,  (x2-x1) = -dx12
        t13 = self.G * self.m3 * ((-dx13) * px1 + (-dy13) * py1) / r13**3
        t12 = self.G * self.m2 * ((-dx12) * px1 + (-dy12) * py1) / r12**3
        return t13 - t12

    def K2(self, Z):
        """{H12, H23}: tidal competition at body 2."""
        px2, py2 = Z[:, 8], Z[:, 9]
        dx12, dy12, r12, _, _, _, dx23, dy23, r23 = self._dists(Z)
        # (x2-x1) = -dx12,  (x2-x3) = dx23
        t12 = self.G * self.m1 * ((-dx12) * px2 + (-dy12) * py2) / r12**3
        t23 = self.G * self.m3 * (dx23 * px2 + dy23 * py2) / r23**3
        return t12 - t23

    def K3(self, Z):
        """{H13, H23}: tidal competition at body 3."""
        px3, py3 = Z[:, 10], Z[:, 11]
        _, _, _, dx13, dy13, r13, dx23, dy23, r23 = self._dists(Z)
        # (x3-x1) = -dx13,  (x3-x2) = -dx23
        t13 = self.G * self.m1 * ((-dx13) * px3 + (-dy13) * py3) / r13**3
        t23 = self.G * self.m2 * ((-dx23) * px3 + (-dy23) * py3) / r23**3
        return t13 - t23

    def get_generators(self):
        """Return (level_0_list, level_1_list) of (name, func, level, accuracy)."""
        L0 = [
            ("H12", self.H12, 0, MACHINE_EPS),
            ("H13", self.H13, 0, MACHINE_EPS),
            ("H23", self.H23, 0, MACHINE_EPS),
        ]
        L1 = [
            ("K1", self.K1, 1, MACHINE_EPS),
            ("K2", self.K2, 1, MACHINE_EPS),
            ("K3", self.K3, 1, MACHINE_EPS),
        ]
        return L0, L1


# =============================================================================
# Numerical Poisson bracket
# =============================================================================
def make_poisson_bracket(f_func, g_func,
                         f_acc=MACHINE_EPS, g_acc=MACHINE_EPS):
    """
    Build a numerical Poisson bracket {f, g} via central finite differences.

    The step size *eps* is adapted to the accuracy of the inputs:
      - For exact inputs:    eps ~ 1e-7,  bracket accuracy ~ 1e-14
      - For inputs with error alpha:  eps ~ alpha^(1/3),
        bracket accuracy ~ alpha^(2/3)

    Returns (bracket_func, bracket_accuracy).
    """
    base_acc = max(f_acc, g_acc)

    if base_acc < 1e-14:                 # inputs are essentially exact
        eps = 1e-7
        bracket_acc = eps**2             # ~1e-14
    else:
        eps = max(base_acc ** (1.0 / 3.0), 1e-7)
        bracket_acc = max(eps**2, base_acc ** (2.0 / 3.0))

    def bracket(Z):
        Z = np.asarray(Z, dtype=np.float64)
        N = Z.shape[0]
        result = np.zeros(N)

        for qi, pi in CANON_PAIRS:
            # --- perturbations along q_i ---
            Zp = Z.copy();  Zp[:, qi] += eps
            Zm = Z.copy();  Zm[:, qi] -= eps
            f_pq = f_func(Zp);  f_mq = f_func(Zm)
            g_pq = g_func(Zp);  g_mq = g_func(Zm)
            df_dq = (f_pq - f_mq) / (2.0 * eps)
            dg_dq = (g_pq - g_mq) / (2.0 * eps)

            # --- perturbations along p_i ---
            Zp = Z.copy();  Zp[:, pi] += eps
            Zm = Z.copy();  Zm[:, pi] -= eps
            f_pp = f_func(Zp);  f_mp = f_func(Zm)
            g_pp = g_func(Zp);  g_mp = g_func(Zm)
            df_dp = (f_pp - f_mp) / (2.0 * eps)
            dg_dp = (g_pp - g_mp) / (2.0 * eps)

            # {f, g} += df/dq * dg/dp  -  df/dp * dg/dq
            result += df_dq * dg_dp - df_dp * dg_dq

        return result

    return bracket, bracket_acc


# =============================================================================
# Linear independence testing
# =============================================================================
def is_independent(eval_matrix, new_col, tol=0.01):
    """
    Check whether *new_col* is linearly independent of the columns
    already in *eval_matrix*.

    Method: project *new_col* onto the orthogonal complement of
    col(eval_matrix) via a thin QR factorisation.  If the residual
    is large relative to the original vector, the column is new.
    """
    v = new_col.ravel()
    norm_v = np.linalg.norm(v)
    if norm_v < 1e-12:
        return False
    if eval_matrix.shape[1] == 0:
        return True

    Q, _ = np.linalg.qr(eval_matrix, mode="reduced")
    projection = Q @ (Q.T @ v)
    residual = np.linalg.norm(v - projection)
    return (residual / norm_v) > tol


# =============================================================================
# Verification helpers
# =============================================================================
def verify_level1(algebra, Z):
    """Compare analytical K_i against finite-difference {H_ab, H_ac}."""
    print("\n  Verifying level-1 formulas (analytical vs finite-difference)...")
    checks = [
        ("K1 = {H12,H13}", algebra.K1, algebra.H12, algebra.H13),
        ("K2 = {H12,H23}", algebra.K2, algebra.H12, algebra.H23),
        ("K3 = {H13,H23}", algebra.K3, algebra.H13, algebra.H23),
    ]
    ok = True
    for label, k_func, ha, hb in checks:
        analytical = k_func(Z)
        numerical, _ = make_poisson_bracket(ha, hb)
        numerical_vals = numerical(Z)
        scale = np.max(np.abs(analytical)) + 1e-15
        err = np.max(np.abs(analytical - numerical_vals)) / scale
        status = "ok" if err < 1e-3 else "FAIL"
        print(f"    {label}: max rel error = {err:.2e}  [{status}]")
        if err >= 1e-5:
            ok = False
    return ok


def verify_jacobi(algebra, Z):
    """
    Check the Jacobi identity
        {H12, K3} - {H13, K2} + {H23, K1} = 0
    """
    print("\n  Jacobi identity check...")
    pb1, _ = make_poisson_bracket(algebra.H12, algebra.K3)
    pb2, _ = make_poisson_bracket(algebra.H13, algebra.K2)
    pb3, _ = make_poisson_bracket(algebra.H23, algebra.K1)
    v1, v2, v3 = pb1(Z), pb2(Z), pb3(Z)
    jacobi = v1 - v2 + v3
    scale = np.max(np.abs(np.column_stack([v1, v2, v3]))) + 1e-15
    violation = np.max(np.abs(jacobi)) / scale
    status = "ok" if violation < 1e-3 else "FAIL"
    print(f"    {'{'}H12,K3{'}'} - {'{'}H13,K2{'}'} + {'{'}H23,K1{'}'} = 0")
    print(f"    Max relative violation: {violation:.2e}  [{status}]")
    return violation < 1e-3


# =============================================================================
# Core: compute the algebra growth level-by-level
# =============================================================================
def compute_growth(algebra, max_level=4, n_samples=200,
                   seed=42, indep_tol=0.01):
    """
    Iteratively compute Poisson brackets and count the dimension
    of the generated Lie algebra at each bracket level.

    Returns
    -------
    results : list of (level, total_dim, n_new, list_of_new_names)
    Z       : sample points used (for downstream checks)
    """
    # ---- sample phase space ------------------------------------------------
    Z = sample_phase_space(n_samples, seed)

    # ---- storage -----------------------------------------------------------
    eval_matrix = np.empty((n_samples, 0))   # each column = generator @ Z
    all_gens = []        # (name, func, level, accuracy)
    computed_pairs = set()

    # ---- level 0: analytical H's -------------------------------------------
    L0, L1 = algebra.get_generators()
    for name, func, level, acc in L0:
        col = func(Z).reshape(-1, 1)
        all_gens.append((name, func, level, acc))
        eval_matrix = np.hstack([eval_matrix, col])

    # mark level-0 intra-brackets as "computed" (they produce level 1)
    for i in range(len(L0)):
        for j in range(i + 1, len(L0)):
            computed_pairs.add(frozenset({i, j}))

    # ---- level 1: analytical K's -------------------------------------------
    verify_level1(algebra, Z)
    verify_jacobi(algebra, Z)

    n_new_1 = 0
    for name, func, level, acc in L1:
        col = func(Z)
        if is_independent(eval_matrix, col, tol=indep_tol):
            all_gens.append((name, func, level, acc))
            eval_matrix = np.hstack([eval_matrix, col.reshape(-1, 1)])
            n_new_1 += 1

    results = [
        (0, 3, 3, ["H12", "H13", "H23"]),
        (1, len(all_gens), n_new_1, ["K1", "K2", "K3"][:n_new_1]),
    ]
    print(f"\n  Level 0: dim = {3:>4d}  (3 generators: H12, H13, H23)")
    print(f"  Level 1: dim = {len(all_gens):>4d}  "
          f"(+{n_new_1} new: K1, K2, K3)")

    # ---- levels 2 … max_level: numerical brackets --------------------------
    frontier_start = 3
    frontier_end = len(all_gens)

    for level in range(2, max_level + 1):
        t0 = time()
        n_candidates = 0
        n_new = 0
        new_names = []
        new_start = len(all_gens)

        # Snapshot: only bracket frontier with generators that existed
        # BEFORE this level.  Brackets with newly-added level-L generators
        # belong to level L+1, not level L.
        n_existing = len(all_gens)

        for i in range(frontier_start, frontier_end):
            for j in range(n_existing):
                if i == j:
                    continue
                pair = frozenset({i, j})
                if pair in computed_pairs:
                    continue
                computed_pairs.add(pair)

                name_i, func_i, _, acc_i = all_gens[i]
                name_j, func_j, _, acc_j = all_gens[j]

                pb_func, pb_acc = make_poisson_bracket(
                    func_i, func_j, acc_i, acc_j
                )
                col = pb_func(Z)
                n_candidates += 1

                if is_independent(eval_matrix, col, tol=indep_tol):
                    short = f"L{level}_{n_new + 1}"
                    full  = f"{{{name_i},{name_j}}}"
                    all_gens.append((short, pb_func, level, pb_acc))
                    eval_matrix = np.hstack([eval_matrix, col.reshape(-1, 1)])
                    new_names.append(f"{short} = {full}")
                    n_new += 1

        elapsed = time() - t0
        total_dim = len(all_gens)
        results.append((level, total_dim, n_new, new_names))

        frontier_start = new_start
        frontier_end = len(all_gens)

        # Estimate worst accuracy at this level
        level_accs = [a for (_, _, lv, a) in all_gens if lv == level]
        worst_acc = max(level_accs) if level_accs else 0.0

        print(f"  Level {level}: dim = {total_dim:>4d}  "
              f"(+{n_new:>3d} new from {n_candidates:>4d} candidates)  "
              f"[{elapsed:>6.1f}s]  acc~{worst_acc:.0e}")

        # Show the first few new generators
        show_limit = 10
        for nm in new_names[:show_limit]:
            print(f"           + {nm}")
        if len(new_names) > show_limit:
            print(f"           ... and {len(new_names) - show_limit} more")

        if n_new == 0:
            print(f"\n  *** ALGEBRA CLOSED at dimension {total_dim} ***")
            break

    return results, Z


# =============================================================================
# Growth analysis
# =============================================================================
def analyze_growth(results):
    """Compute ratios, fits, and growth-type classification."""
    levels = [r[0] for r in results]
    dims   = [r[1] for r in results]
    new_counts = [r[2] for r in results]

    analysis = dict(levels=levels, dims=dims, new_counts=new_counts)

    # dimension ratios  d(L) / d(L-1)
    ratios = []
    for i in range(1, len(dims)):
        ratios.append(dims[i] / dims[i - 1] if dims[i - 1] > 0 else float("inf"))
    analysis["ratios"] = ratios

    # new-count ratios  new(L) / new(L-1)
    inc_ratios = []
    for i in range(1, len(new_counts)):
        if new_counts[i - 1] > 0:
            inc_ratios.append(new_counts[i] / new_counts[i - 1])
    analysis["inc_ratios"] = inc_ratios

    # exponential fit  d(L) ~ a * b^L
    if len(dims) >= 3:
        try:
            d = np.array(dims, dtype=float)
            l = np.array(levels, dtype=float)
            mask = d > 0
            coeffs = np.polyfit(l[mask], np.log(d[mask]), 1)
            analysis["exp_base"]  = np.exp(coeffs[0])
            analysis["exp_coeff"] = np.exp(coeffs[1])
        except Exception:
            pass

    return analysis


def print_analysis(all_results):
    """Print a table summarising growth across configurations."""
    print("\n" + "=" * 70)
    print("GROWTH ANALYSIS SUMMARY")
    print("=" * 70)

    for label, (results, _) in all_results.items():
        a = analyze_growth(results)
        print(f"\n  {label}")
        header = (f"  {'Level':>5} | {'Dim':>5} | {'New':>5} "
                  f"| {'d(L)/d(L-1)':>12} | {'New(L)/New(L-1)':>16}")
        print(header)
        print(f"  {'-'*5}-+-{'-'*5}-+-{'-'*5}"
              f"-+-{'-'*12}-+-{'-'*16}")

        for i, (lv, dim, nc, _) in enumerate(results):
            r_str  = f"{a['ratios'][i-1]:.2f}"  if i > 0 else "-"
            ir_str = f"{a['inc_ratios'][i-1]:.2f}" if i >= 1 and (i-1) < len(a['inc_ratios']) else "-"
            print(f"  {lv:>5} | {dim:>5} | {nc:>5} "
                  f"| {r_str:>12} | {ir_str:>16}")

        if "exp_base" in a:
            print(f"\n  Exponential fit: d(L) ~ "
                  f"{a['exp_coeff']:.1f} * {a['exp_base']:.2f}^L")

        # classify
        if len(a["ratios"]) >= 2:
            avg = np.mean(a["ratios"][-2:])
            if avg > 1.8:
                gtype = "EXPONENTIAL"
            elif avg > 1.2:
                gtype = "SUPER-LINEAR"
            elif avg > 1.02:
                gtype = "SUB-LINEAR / POLYNOMIAL"
            else:
                gtype = "SATURATING / CLOSED"
            print(f"  Growth pattern: {gtype}  (recent avg ratio {avg:.2f})")


# =============================================================================
# Visualisation
# =============================================================================
def plot_growth(all_results, save_path="algebra_growth.png"):
    """Create a 4-panel growth-characterisation figure."""
    if not HAS_MPL:
        print("\n  matplotlib not available — skipping plot.")
        return

    fig, axes = plt.subplots(2, 2, figsize=(13, 10))
    fig.suptitle("Three-Body Lie Algebra Growth Characterisation",
                 fontsize=14, fontweight="bold", y=0.98)
    colors = plt.cm.tab10.colors

    # --- panel 1: dimension (linear) ----------------------------------------
    ax = axes[0, 0]
    for idx, (label, (results, _)) in enumerate(all_results.items()):
        lvls = [r[0] for r in results]
        dims = [r[1] for r in results]
        ax.plot(lvls, dims, "o-", color=colors[idx], label=label,
                markersize=8, linewidth=2)
    ax.set_xlabel("Bracket level L")
    ax.set_ylabel("Algebra dimension d(L)")
    ax.set_title("Cumulative dimension")
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3)

    # --- panel 2: dimension (log) -------------------------------------------
    ax = axes[0, 1]
    for idx, (label, (results, _)) in enumerate(all_results.items()):
        lvls = [r[0] for r in results]
        dims = [r[1] for r in results]
        ax.semilogy(lvls, dims, "o-", color=colors[idx], label=label,
                    markersize=8, linewidth=2)
        a = analyze_growth(results)
        if "exp_base" in a and len(lvls) >= 3:
            fit_x = np.linspace(lvls[0], lvls[-1], 50)
            fit_y = a["exp_coeff"] * a["exp_base"] ** fit_x
            ax.semilogy(fit_x, fit_y, "--", color=colors[idx], alpha=0.4)
    ax.set_xlabel("Bracket level L")
    ax.set_ylabel("d(L)  [log scale]")
    ax.set_title("Growth rate (log scale)")
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3)

    # --- panel 3: new generators per level ----------------------------------
    ax = axes[1, 0]
    n_cfg = len(all_results)
    bw = 0.8 / max(n_cfg, 1)
    for idx, (label, (results, _)) in enumerate(all_results.items()):
        lvls = [r[0] for r in results]
        ncs  = [r[2] for r in results]
        offset = (idx - n_cfg / 2 + 0.5) * bw
        ax.bar([l + offset for l in lvls], ncs,
               width=bw, color=colors[idx], label=label, alpha=0.8)
    ax.set_xlabel("Bracket level L")
    ax.set_ylabel("New independent generators")
    ax.set_title("New generators per level")
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3, axis="y")

    # --- panel 4: growth ratio ----------------------------------------------
    ax = axes[1, 1]
    for idx, (label, (results, _)) in enumerate(all_results.items()):
        a = analyze_growth(results)
        if a["ratios"]:
            rx = list(range(1, len(a["ratios"]) + 1))
            ax.plot(rx, a["ratios"], "o-", color=colors[idx],
                    label=label, markersize=8, linewidth=2)
    ax.set_xlabel("Bracket level L")
    ax.set_ylabel("d(L) / d(L-1)")
    ax.set_title("Dimension growth ratio  (constant = exponential)")
    ax.axhline(y=1.0, color="gray", linestyle="--", alpha=0.5)
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3)

    plt.tight_layout(rect=[0, 0, 1, 0.96])
    plt.savefig(save_path, dpi=150, bbox_inches="tight")
    print(f"\n  Plot saved to: {save_path}")
    plt.close()


# =============================================================================
# Main
# =============================================================================
def main():
    ap = argparse.ArgumentParser(
        description="Three-Body Lie Algebra Growth Characterisation")
    ap.add_argument("--max-level", type=int, default=4,
                    help="Maximum bracket level (default: 4)")
    ap.add_argument("--samples", type=int, default=200,
                    help="Phase-space sample points (default: 200)")
    ap.add_argument("--seed", type=int, default=42,
                    help="Random seed (default: 42)")
    ap.add_argument("--tol", type=float, default=0.01,
                    help="Independence tolerance (default: 0.01)")
    args = ap.parse_args()

    print("=" * 70)
    print("THREE-BODY LIE ALGEBRA GROWTH CHARACTERISATION")
    print("=" * 70)
    print(f"""
  Goal: determine how the Lie algebra generated by the three pairwise
  Hamiltonians grows under iterated Poisson brackets.

  Parameters
    max_level  = {args.max_level}
    samples    = {args.samples}
    seed       = {args.seed}
    tolerance  = {args.tol}
    """)

    configs = [
        ("Equal masses (1:1:1)",       1.0,    1.0,   1.0),
        ("Hierarchical (1000:1:0.3)",  1000.0, 1.0,   0.3),
        ("Restricted (1:1:0.001)",     1.0,    1.0,   0.001),
    ]

    all_results = {}
    t_total = time()

    for label, m1, m2, m3 in configs:
        print(f"\n{'=' * 70}")
        print(f"  {label}   (m1={m1}, m2={m2}, m3={m3}, G=1)")
        print(f"{'=' * 70}")

        algebra = ThreeBodyAlgebra(m1=m1, m2=m2, m3=m3, G=1.0)
        results, Z = compute_growth(
            algebra,
            max_level=args.max_level,
            n_samples=args.samples,
            seed=args.seed,
            indep_tol=args.tol,
        )
        all_results[label] = (results, Z)

    print_analysis(all_results)
    plot_growth(all_results)

    print("\n" + "=" * 70)
    print("INTERPRETATION GUIDE")
    print("=" * 70)
    print("""
  EXPONENTIAL growth  (ratio >> 1 and roughly constant)
      New independent generators multiply at each level.
      This mirrors Lyapunov divergence: the system's algebraic
      complexity grows as fast as its dynamical chaos.

  POLYNOMIAL growth  (ratio --> 1)
      Growth decelerates — hidden algebraic constraints limit
      the chaos. Residual structure in the dynamics.

  MASS-DEPENDENT variation
      If the growth rate differs across mass configurations, the
      algebraic complexity is tied to the physical setup. Near-
      integrable limits (e.g. restricted 3-body) should show
      slower growth than the equal-mass (fully chaotic) case.

  The growth rate connects to the *Gelfand-Kirillov dimension*
  of the generated algebra — a standard invariant in algebra
  theory that measures "how infinite" an infinite-dimensional
  algebra is.
    """)

    elapsed_total = time() - t_total
    print(f"  Total runtime: {elapsed_total:.1f}s")


if __name__ == "__main__":
    main()
