#!/usr/bin/env python3
"""
Calogero-Moser vs Gravitational: Bracket Algebra Comparison
=============================================================

THE critical experiment for the paper's non-integrability claim.

Compares the Poisson bracket algebra generated by pairwise Hamiltonians
for two planar 3-body systems:

  1. GRAVITATIONAL:  V_ij = -G*m_i*m_j / r_ij     (non-integrable)
  2. CALOGERO-MOSER: V_ij = +g^2 / r_ij^2          (completely integrable)

If both systems produce the same dimension sequence AND the same SVD gap
structure, then bracket-algebra growth alone does NOT distinguish
integrability from non-integrability.

If the SVD gap closes or the dimension differs at level 3, the paper's
methodology has genuine discriminating power.

Known results from prior computation:
  Both systems: d(0)=3, d(1)=6, d(2)=17
  Gravitational d(3)=116 (from preprint)
  CM d(3) = ???  <-- THIS IS WHAT WE'RE COMPUTING

Usage:
    python cm_comparison.py
    python cm_comparison.py --max-level 3 --samples 300
"""

import numpy as np
import argparse
import os
from time import time

os.environ["PYTHONUNBUFFERED"] = "1"

NDIM = 12
CANON_PAIRS = [(0, 6), (1, 7), (2, 8), (3, 9), (4, 10), (5, 11)]
MACHINE_EPS = float(np.finfo(np.float64).eps)


# =============================================================================
# Phase-space sampling
# =============================================================================
def sample_phase_space(n, seed=42, pos_range=3.0, mom_range=1.0, min_sep=0.5):
    rng = np.random.RandomState(seed)
    points = np.empty((0, NDIM))
    for _ in range(200):
        batch_size = max((n - points.shape[0]) * 5, 256)
        batch = np.zeros((batch_size, NDIM))
        batch[:, :6] = rng.uniform(-pos_range, pos_range, (batch_size, 6))
        batch[:, 6:] = rng.uniform(-mom_range, mom_range, (batch_size, 6))
        dx12 = batch[:, 0] - batch[:, 2]
        dy12 = batch[:, 1] - batch[:, 3]
        dx13 = batch[:, 0] - batch[:, 4]
        dy13 = batch[:, 1] - batch[:, 5]
        dx23 = batch[:, 2] - batch[:, 4]
        dy23 = batch[:, 3] - batch[:, 5]
        r12 = np.sqrt(dx12**2 + dy12**2)
        r13 = np.sqrt(dx13**2 + dy13**2)
        r23 = np.sqrt(dx23**2 + dy23**2)
        good = (r12 > min_sep) & (r13 > min_sep) & (r23 > min_sep)
        points = np.vstack([points, batch[good]])
        if points.shape[0] >= n:
            break
    return points[:n]


# =============================================================================
# Gravitational 3-body Hamiltonians
# =============================================================================
class GravitationalAlgebra:
    """Planar gravitational 3-body: V_ij = -G*m_i*m_j / r_ij"""

    def __init__(self, m1=1.0, m2=1.0, m3=1.0, G=1.0):
        self.m1, self.m2, self.m3, self.G = m1, m2, m3, G
        self.name = "Gravitational"

    def H12(self, Z):
        px1, py1 = Z[:, 6], Z[:, 7]
        px2, py2 = Z[:, 8], Z[:, 9]
        T = (px1**2 + py1**2) / (2 * self.m1) + (px2**2 + py2**2) / (2 * self.m2)
        dx = Z[:, 0] - Z[:, 2]
        dy = Z[:, 1] - Z[:, 3]
        r = np.sqrt(dx**2 + dy**2)
        return T - self.G * self.m1 * self.m2 / r

    def H13(self, Z):
        px1, py1 = Z[:, 6], Z[:, 7]
        px3, py3 = Z[:, 10], Z[:, 11]
        T = (px1**2 + py1**2) / (2 * self.m1) + (px3**2 + py3**2) / (2 * self.m3)
        dx = Z[:, 0] - Z[:, 4]
        dy = Z[:, 1] - Z[:, 5]
        r = np.sqrt(dx**2 + dy**2)
        return T - self.G * self.m1 * self.m3 / r

    def H23(self, Z):
        px2, py2 = Z[:, 8], Z[:, 9]
        px3, py3 = Z[:, 10], Z[:, 11]
        T = (px2**2 + py2**2) / (2 * self.m2) + (px3**2 + py3**2) / (2 * self.m3)
        dx = Z[:, 2] - Z[:, 4]
        dy = Z[:, 3] - Z[:, 5]
        r = np.sqrt(dx**2 + dy**2)
        return T - self.G * self.m2 * self.m3 / r

    def K1(self, Z):
        """{H12, H13}"""
        px1, py1 = Z[:, 6], Z[:, 7]
        dx12 = Z[:, 0] - Z[:, 2]; dy12 = Z[:, 1] - Z[:, 3]
        dx13 = Z[:, 0] - Z[:, 4]; dy13 = Z[:, 1] - Z[:, 5]
        r12 = np.sqrt(dx12**2 + dy12**2)
        r13 = np.sqrt(dx13**2 + dy13**2)
        t13 = self.G * self.m3 * ((-dx13) * px1 + (-dy13) * py1) / r13**3
        t12 = self.G * self.m2 * ((-dx12) * px1 + (-dy12) * py1) / r12**3
        return t13 - t12

    def K2(self, Z):
        """{H12, H23}"""
        px2, py2 = Z[:, 8], Z[:, 9]
        dx12 = Z[:, 0] - Z[:, 2]; dy12 = Z[:, 1] - Z[:, 3]
        dx23 = Z[:, 2] - Z[:, 4]; dy23 = Z[:, 3] - Z[:, 5]
        r12 = np.sqrt(dx12**2 + dy12**2)
        r23 = np.sqrt(dx23**2 + dy23**2)
        t12 = self.G * self.m1 * ((-dx12) * px2 + (-dy12) * py2) / r12**3
        t23 = self.G * self.m3 * (dx23 * px2 + dy23 * py2) / r23**3
        return t12 - t23

    def K3(self, Z):
        """{H13, H23}"""
        px3, py3 = Z[:, 10], Z[:, 11]
        dx13 = Z[:, 0] - Z[:, 4]; dy13 = Z[:, 1] - Z[:, 5]
        dx23 = Z[:, 2] - Z[:, 4]; dy23 = Z[:, 3] - Z[:, 5]
        r13 = np.sqrt(dx13**2 + dy13**2)
        r23 = np.sqrt(dx23**2 + dy23**2)
        t13 = self.G * self.m1 * ((-dx13) * px3 + (-dy13) * py3) / r13**3
        t23 = self.G * self.m2 * ((-dx23) * px3 + (-dy23) * py3) / r23**3
        return t13 - t23


# =============================================================================
# Calogero-Moser 3-body Hamiltonians
# =============================================================================
class CalogeroMoserAlgebra:
    """
    Planar Calogero-Moser 3-body: V_ij = g^2 / r_ij^2

    This system is COMPLETELY INTEGRABLE (Moser 1975, Calogero 1971).
    It has a Lax pair representation and explicit action-angle variables.
    """

    def __init__(self, m1=1.0, m2=1.0, m3=1.0, g=1.0):
        self.m1, self.m2, self.m3, self.g = m1, m2, m3, g
        self.name = "Calogero-Moser"

    def H12(self, Z):
        px1, py1 = Z[:, 6], Z[:, 7]
        px2, py2 = Z[:, 8], Z[:, 9]
        T = (px1**2 + py1**2) / (2 * self.m1) + (px2**2 + py2**2) / (2 * self.m2)
        dx = Z[:, 0] - Z[:, 2]
        dy = Z[:, 1] - Z[:, 3]
        r2 = dx**2 + dy**2
        return T + self.g**2 / r2

    def H13(self, Z):
        px1, py1 = Z[:, 6], Z[:, 7]
        px3, py3 = Z[:, 10], Z[:, 11]
        T = (px1**2 + py1**2) / (2 * self.m1) + (px3**2 + py3**2) / (2 * self.m3)
        dx = Z[:, 0] - Z[:, 4]
        dy = Z[:, 1] - Z[:, 5]
        r2 = dx**2 + dy**2
        return T + self.g**2 / r2

    def H23(self, Z):
        px2, py2 = Z[:, 8], Z[:, 9]
        px3, py3 = Z[:, 10], Z[:, 11]
        T = (px2**2 + py2**2) / (2 * self.m2) + (px3**2 + py3**2) / (2 * self.m3)
        dx = Z[:, 2] - Z[:, 4]
        dy = Z[:, 3] - Z[:, 5]
        r2 = dx**2 + dy**2
        return T + self.g**2 / r2

    def K1(self, Z):
        """{H12, H13} for CM system"""
        px1, py1 = Z[:, 6], Z[:, 7]
        dx12 = Z[:, 0] - Z[:, 2]; dy12 = Z[:, 1] - Z[:, 3]
        dx13 = Z[:, 0] - Z[:, 4]; dy13 = Z[:, 1] - Z[:, 5]
        r12_2 = dx12**2 + dy12**2
        r13_2 = dx13**2 + dy13**2
        # dV12/dx1 = -2*g^2 * dx12 / r12^4
        # dV13/dx1 = -2*g^2 * dx13 / r13^4
        # {H12, H13} = (1/m1) * [(dV13/dx1 - dV12/dx1)*px1 + (dV13/dy1 - dV12/dy1)*py1]
        # Wait, need to be more careful. Let me compute this via the Poisson bracket directly.
        # {H12, H13} = sum_k (dH12/dq_k * dH13/dp_k - dH12/dp_k * dH13/dq_k)
        # H12 = T1 + T2 + g^2/r12^2
        # H13 = T1 + T3 + g^2/r13^2
        # dH12/dx1 = -2g^2 * dx12 / r12^4,  dH12/dpx1 = px1/m1
        # dH13/dx1 = -2g^2 * dx13 / r13^4,  dH13/dpx1 = px1/m1
        # The bracket only gets contributions from shared body 1
        # {H12, H13} = (1/m1) * [(-2g^2 dx13/r13^4) * px1 - (-2g^2 dx12/r12^4) * px1
        #              + (-2g^2 dy13/r13^4) * py1 - (-2g^2 dy12/r12^4) * py1]
        # = (2g^2/m1) * [(dx12/r12^4 - dx13/r13^4)*px1 + (dy12/r12^4 - dy13/r13^4)*py1]
        coeff = 2 * self.g**2 / self.m1
        fx = coeff * (dx13 / r13_2**2 - dx12 / r12_2**2)
        fy = coeff * (dy13 / r13_2**2 - dy12 / r12_2**2)
        return fx * px1 + fy * py1

    def K2(self, Z):
        """{H12, H23} for CM system"""
        px2, py2 = Z[:, 8], Z[:, 9]
        dx12 = Z[:, 0] - Z[:, 2]; dy12 = Z[:, 1] - Z[:, 3]
        dx23 = Z[:, 2] - Z[:, 4]; dy23 = Z[:, 3] - Z[:, 5]
        r12_2 = dx12**2 + dy12**2
        r23_2 = dx23**2 + dy23**2
        # dH12/dx2 = -2g^2 * (-dx12) / r12^4 = 2g^2 * dx12 / r12^4
        # (since dx12 = x1-x2, so d/dx2 of (x1-x2)^2 = -2(x1-x2) = -2*dx12)
        # dH12/dx2 = -2g^2 * d/dx2[(x1-x2)^2 + (y1-y2)^2] / r12^4 ... let me redo
        # V12 = g^2 / r12^2, r12^2 = (x1-x2)^2 + (y1-y2)^2
        # dV12/dx2 = g^2 * (-2)(x1-x2)*(-1) / r12^4 = 2g^2 * dx12 / r12^4
        # dH23/dx2 = -2g^2 * dx23 / r23^4  (since dx23 = x2-x3, d/dx2 gives -2*dx23)
        # Wait: dV23/dx2 = g^2 * (-2)(x2-x3)*(1) / r23^4 = -2g^2 * dx23 / r23^4
        # {H12, H23}: shared body is 2
        # = (1/m2) * [(dV12/dx2)*px2 - (dV23/dx2)*px2 + (dV12/dy2)*py2 - (dV23/dy2)*py2]
        # Actually: {H12, H23} = sum (dH12/dq * dH23/dp - dH12/dp * dH23/dq)
        # Body 2 terms: dH12/dx2 * dH23/dpx2 - dH12/dpx2 * dH23/dx2
        #             = (2g^2 dx12/r12^4) * (px2/m2) - (px2/m2) * (-2g^2 dx23/r23^4)
        #             = (px2/m2) * 2g^2 * (dx12/r12^4 + dx23/r23^4)
        # Hmm wait. Let me be more careful:
        # dH12/dx2 = d/dx2[T1+T2+g^2/r12^2]
        # r12^2 = (x1-x2)^2 + (y1-y2)^2
        # d(g^2/r12^2)/dx2 = g^2 * (-1/r12^4) * 2*(x1-x2)*(-1) = 2g^2*(x1-x2)/r12^4
        # = 2g^2 * dx12 / r12^4  (since dx12 = x1-x2)
        #
        # dH23/dx2 = d/dx2[T2+T3+g^2/r23^2]
        # r23^2 = (x2-x3)^2 + (y2-y3)^2
        # d(g^2/r23^2)/dx2 = g^2 * (-1/r23^4) * 2*(x2-x3)*(1) = -2g^2*(x2-x3)/r23^4
        # = -2g^2 * dx23 / r23^4  (since dx23 = x2-x3)
        #
        # Body 2 contribution to {H12, H23}:
        # dH12/dx2 * dH23/dpx2 - dH12/dpx2 * dH23/dx2
        # = (2g^2*dx12/r12^4)*(px2/m2) - (px2/m2)*(-2g^2*dx23/r23^4)
        # = (2g^2/m2) * (dx12/r12^4 + dx23/r23^4) * px2
        # Same for y
        coeff = 2 * self.g**2 / self.m2
        fx = coeff * (dx12 / r12_2**2 + dx23 / r23_2**2)
        fy = coeff * (dy12 / r12_2**2 + dy23 / r23_2**2)
        return fx * px2 + fy * py2

    def K3(self, Z):
        """{H13, H23} for CM system"""
        px3, py3 = Z[:, 10], Z[:, 11]
        dx13 = Z[:, 0] - Z[:, 4]; dy13 = Z[:, 1] - Z[:, 5]
        dx23 = Z[:, 2] - Z[:, 4]; dy23 = Z[:, 3] - Z[:, 5]
        r13_2 = dx13**2 + dy13**2
        r23_2 = dx23**2 + dy23**2
        # dH13/dx3: r13^2 = (x1-x3)^2+(y1-y3)^2, dx13=x1-x3
        # d(g^2/r13^2)/dx3 = g^2*(-1/r13^4)*2*(x1-x3)*(-1) = 2g^2*dx13/r13^4
        # dH23/dx3: r23^2 = (x2-x3)^2+(y2-y3)^2, dx23=x2-x3
        # d(g^2/r23^2)/dx3 = g^2*(-1/r23^4)*2*(x2-x3)*(-1) = 2g^2*dx23/r23^4
        # Body 3 contribution:
        # dH13/dx3 * dH23/dpx3 - dH13/dpx3 * dH23/dx3
        # = (2g^2*dx13/r13^4)*(px3/m3) - (px3/m3)*(2g^2*dx23/r23^4)
        # = (2g^2/m3)*(dx13/r13^4 - dx23/r23^4)*px3
        coeff = 2 * self.g**2 / self.m3
        fx = coeff * (dx13 / r13_2**2 - dx23 / r23_2**2)
        fy = coeff * (dy13 / r13_2**2 - dy23 / r23_2**2)
        return fx * px3 + fy * py3


# =============================================================================
# Numerical Poisson bracket via central finite differences
# =============================================================================
def make_poisson_bracket(f_func, g_func, f_acc=MACHINE_EPS, g_acc=MACHINE_EPS):
    base_acc = max(f_acc, g_acc)
    if base_acc < 1e-14:
        eps = 1e-7
        bracket_acc = eps**2
    else:
        eps = max(base_acc ** (1.0 / 3.0), 1e-7)
        bracket_acc = max(eps**2, base_acc ** (2.0 / 3.0))

    def bracket(Z):
        Z = np.asarray(Z, dtype=np.float64)
        N = Z.shape[0]
        result = np.zeros(N)
        for qi, pi in CANON_PAIRS:
            Zp = Z.copy(); Zp[:, qi] += eps
            Zm = Z.copy(); Zm[:, qi] -= eps
            df_dq = (f_func(Zp) - f_func(Zm)) / (2.0 * eps)
            dg_dq = (g_func(Zp) - g_func(Zm)) / (2.0 * eps)
            Zp = Z.copy(); Zp[:, pi] += eps
            Zm = Z.copy(); Zm[:, pi] -= eps
            df_dp = (f_func(Zp) - f_func(Zm)) / (2.0 * eps)
            dg_dp = (g_func(Zp) - g_func(Zm)) / (2.0 * eps)
            result += df_dq * dg_dp - df_dp * dg_dq
        return result

    return bracket, bracket_acc


# =============================================================================
# Independence test via QR projection
# =============================================================================
def is_independent(eval_matrix, new_col, tol=0.01):
    v = new_col.ravel()
    norm_v = np.linalg.norm(v)
    if norm_v < 1e-12:
        return False
    if eval_matrix.shape[1] == 0:
        return True
    Q, _ = np.linalg.qr(eval_matrix, mode="reduced")
    projection = Q @ (Q.T @ v)
    residual = np.linalg.norm(v - projection)
    return (residual / norm_v) > tol


# =============================================================================
# SVD gap analysis
# =============================================================================
def svd_gap_analysis(eval_matrix, label=""):
    norms = np.linalg.norm(eval_matrix, axis=0)
    norms[norms < 1e-15] = 1.0
    M = eval_matrix / norms
    U, s, Vt = np.linalg.svd(M, full_matrices=False)

    noise_threshold = 1e-8 * s[0]
    n_meaningful = int(np.sum(s > noise_threshold))

    best_gap_ratio = 1.0
    best_gap_idx = -1
    for i in range(min(n_meaningful, len(s) - 1)):
        if s[i + 1] > noise_threshold:
            gap = s[i] / s[i + 1]
        else:
            gap = s[i] / max(s[i + 1], 1e-300)
        if gap > best_gap_ratio and i >= 2:
            best_gap_ratio = gap
            best_gap_idx = i

    # Compact output
    print(f"\n  SVD {label}:")
    # Show singular values around key indices and the gap
    key_indices = {2, 5, 16, 68, 115}
    if best_gap_idx >= 0:
        for di in range(-2, 3):
            key_indices.add(best_gap_idx + di)

    for i in range(min(len(s), 130)):
        if i < 20 or i in key_indices or i >= len(s) - 3:
            if i < len(s) - 1 and s[i + 1] > 1e-300:
                gap = s[i] / s[i + 1]
            else:
                gap = float("inf")
            marker = ""
            if i + 1 == 3: marker = "  <-- 3"
            elif i + 1 == 6: marker = "  <-- 6"
            elif i + 1 == 17: marker = "  <-- 17"
            elif i + 1 == 116: marker = "  <-- 116"
            if i == best_gap_idx:
                marker += f"  *** GAP ({gap:.2e}) ***"
            print(f"    sv[{i+1:>3d}] = {s[i]:.8e}  gap={gap:.2e}{marker}")

    if best_gap_ratio > 1e4:
        rank = best_gap_idx + 1
        print(f"  DEFINITIVE GAP at rank {rank}: ratio {best_gap_ratio:.2e}")
    elif best_gap_ratio > 10:
        rank = best_gap_idx + 1
        print(f"  Gap at rank {rank}: ratio {best_gap_ratio:.1f} (moderate)")
    else:
        rank = n_meaningful
        print(f"  No clear gap (best ratio {best_gap_ratio:.1f}), "
              f"using noise floor: rank={rank}")

    return rank, s, best_gap_ratio


# =============================================================================
# Compute bracket algebra for a given system
# =============================================================================
def compute_algebra(system, Z, max_level=3, indep_tol=0.01):
    """
    Compute the bracket algebra for a system (GravitationalAlgebra or
    CalogeroMoserAlgebra) and return (generators, eval_matrix, level_info).
    """
    name = system.name
    print(f"\n{'='*70}")
    print(f"  {name} system")
    print(f"{'='*70}")

    n_samples = Z.shape[0]
    eval_matrix = np.empty((n_samples, 0))
    all_gens = []  # (name, func, level, accuracy)
    computed_pairs = set()

    # Level 0
    L0 = [
        ("H12", system.H12, 0, MACHINE_EPS),
        ("H13", system.H13, 0, MACHINE_EPS),
        ("H23", system.H23, 0, MACHINE_EPS),
    ]
    for gname, func, level, acc in L0:
        col = func(Z).reshape(-1, 1)
        all_gens.append((gname, func, level, acc))
        eval_matrix = np.hstack([eval_matrix, col])

    for i in range(3):
        for j in range(i + 1, 3):
            computed_pairs.add(frozenset({i, j}))

    # Level 1: analytical K's
    L1 = [
        ("K1", system.K1, 1, MACHINE_EPS),
        ("K2", system.K2, 1, MACHINE_EPS),
        ("K3", system.K3, 1, MACHINE_EPS),
    ]

    # Verify analytical K's against numerical brackets
    print(f"\n  Verifying level 1 (analytical vs FD)...")
    fd_checks = [
        ("K1={H12,H13}", system.K1, system.H12, system.H13),
        ("K2={H12,H23}", system.K2, system.H12, system.H23),
        ("K3={H13,H23}", system.K3, system.H13, system.H23),
    ]
    for check_label, k_func, ha, hb in fd_checks:
        analytical = k_func(Z)
        fd_bracket, _ = make_poisson_bracket(ha, hb)
        fd_vals = fd_bracket(Z)
        scale = np.max(np.abs(analytical)) + 1e-15
        err = np.max(np.abs(analytical - fd_vals)) / scale
        status = "OK" if err < 1e-3 else "FAIL"
        print(f"    {check_label}: rel err = {err:.2e} [{status}]")

    n_new_1 = 0
    for gname, func, level, acc in L1:
        col = func(Z)
        if is_independent(eval_matrix, col, tol=indep_tol):
            all_gens.append((gname, func, level, acc))
            eval_matrix = np.hstack([eval_matrix, col.reshape(-1, 1)])
            n_new_1 += 1

    print(f"\n  Level 0: dim = {3}")
    print(f"  Level 1: dim = {len(all_gens)}  (+{n_new_1} new)")

    results = [
        (0, 3, 3),
        (1, len(all_gens), n_new_1),
    ]

    # Levels 2+
    frontier_start = 3
    frontier_end = len(all_gens)

    for level in range(2, max_level + 1):
        t0 = time()
        n_candidates = 0
        n_new = 0
        n_existing = len(all_gens)
        new_start = n_existing

        for i in range(frontier_start, frontier_end):
            for j in range(n_existing):
                if i == j:
                    continue
                pair = frozenset({i, j})
                if pair in computed_pairs:
                    continue
                computed_pairs.add(pair)

                name_i, func_i, _, acc_i = all_gens[i]
                name_j, func_j, _, acc_j = all_gens[j]

                pb_func, pb_acc = make_poisson_bracket(func_i, func_j, acc_i, acc_j)
                col = pb_func(Z)
                n_candidates += 1

                if is_independent(eval_matrix, col, tol=indep_tol):
                    short = f"L{level}_{n_new + 1}"
                    all_gens.append((short, pb_func, level, pb_acc))
                    eval_matrix = np.hstack([eval_matrix, col.reshape(-1, 1)])
                    n_new += 1

                if n_candidates % 50 == 0:
                    print(f"    [{name}] Level {level}: {n_candidates} candidates, "
                          f"{n_new} new  [{time()-t0:.1f}s]", flush=True)

        elapsed = time() - t0
        total_dim = len(all_gens)
        results.append((level, total_dim, n_new))

        frontier_start = new_start
        frontier_end = len(all_gens)

        level_accs = [a for (_, _, lv, a) in all_gens if lv == level]
        worst_acc = max(level_accs) if level_accs else 0.0

        print(f"  Level {level}: dim = {total_dim:>4d}  (+{n_new:>3d} new "
              f"from {n_candidates} cands)  [{elapsed:.1f}s]  acc~{worst_acc:.0e}")

    return all_gens, eval_matrix, results


# =============================================================================
# Main comparison
# =============================================================================
def main():
    ap = argparse.ArgumentParser(
        description="Calogero-Moser vs Gravitational bracket algebra comparison")
    ap.add_argument("--max-level", type=int, default=3,
                    help="Maximum bracket level (default: 3)")
    ap.add_argument("--samples", type=int, default=300,
                    help="Phase-space sample points (default: 300)")
    ap.add_argument("--seed", type=int, default=42,
                    help="Random seed (default: 42)")
    ap.add_argument("--tol", type=float, default=0.01,
                    help="Independence tolerance (default: 0.01)")
    args = ap.parse_args()

    print("=" * 70)
    print("CALOGERO-MOSER vs GRAVITATIONAL: BRACKET ALGEBRA COMPARISON")
    print("=" * 70)
    print(f"  Max level: {args.max_level}")
    print(f"  Samples:   {args.samples}")
    print(f"  Seed:      {args.seed}")
    print(f"  Tolerance: {args.tol}")
    print()
    print("  This is the CRITICAL experiment for the paper.")
    print("  If CM d(3) < 116 or SVD gap differs, the methodology works.")
    print("  If CM d(3) = 116 with same gap structure, it does not.")
    print()

    # Use the SAME sample points for both systems (fair comparison)
    Z = sample_phase_space(args.samples, args.seed)
    print(f"  Generated {Z.shape[0]} sample points")

    # Compute both systems
    grav = GravitationalAlgebra(m1=1.0, m2=1.0, m3=1.0, G=1.0)
    cm = CalogeroMoserAlgebra(m1=1.0, m2=1.0, m3=1.0, g=1.0)

    grav_gens, grav_eval, grav_results = compute_algebra(
        grav, Z, max_level=args.max_level, indep_tol=args.tol)
    cm_gens, cm_eval, cm_results = compute_algebra(
        cm, Z, max_level=args.max_level, indep_tol=args.tol)

    # SVD analysis for both
    print(f"\n{'='*70}")
    print("SVD GAP ANALYSIS")
    print(f"{'='*70}")

    grav_svd_results = {}
    cm_svd_results = {}

    for level in range(args.max_level + 1):
        # Gravitational
        grav_mask = [i for i, (_, _, lv, _) in enumerate(grav_gens) if lv <= level]
        if grav_mask:
            g_sub = grav_eval[:, grav_mask]
            g_rank, g_sv, g_gap = svd_gap_analysis(
                g_sub, label=f"Gravitational through level {level}")
            grav_svd_results[level] = (g_rank, g_sv, g_gap)

        # CM
        cm_mask = [i for i, (_, _, lv, _) in enumerate(cm_gens) if lv <= level]
        if cm_mask:
            c_sub = cm_eval[:, cm_mask]
            c_rank, c_sv, c_gap = svd_gap_analysis(
                c_sub, label=f"Calogero-Moser through level {level}")
            cm_svd_results[level] = (c_rank, c_sv, c_gap)

    # Final comparison table
    print(f"\n{'='*70}")
    print("COMPARISON TABLE")
    print(f"{'='*70}")
    print(f"  {'Level':>5} | {'Grav dim':>8} | {'Grav gap':>12} | "
          f"{'CM dim':>8} | {'CM gap':>12} | {'Match?':>7}")
    print(f"  {'-'*5}-+-{'-'*8}-+-{'-'*12}-+-{'-'*8}-+-{'-'*12}-+-{'-'*7}")

    for level in range(args.max_level + 1):
        g_dim = grav_results[level][1] if level < len(grav_results) else "?"
        c_dim = cm_results[level][1] if level < len(cm_results) else "?"
        g_gap = grav_svd_results.get(level, (0, [], 0))[2]
        c_gap = cm_svd_results.get(level, (0, [], 0))[2]
        match = "YES" if g_dim == c_dim else "**NO**"
        print(f"  {level:>5} | {g_dim:>8} | {g_gap:>12.2e} | "
              f"{c_dim:>8} | {c_gap:>12.2e} | {match:>7}")

    # Verdict
    print(f"\n{'='*70}")
    print("VERDICT")
    print(f"{'='*70}")

    g3 = grav_results[-1][1] if len(grav_results) > args.max_level else None
    c3 = cm_results[-1][1] if len(cm_results) > args.max_level else None

    if g3 is not None and c3 is not None:
        if g3 != c3:
            print(f"\n  DIMENSION DIFFERS at level {args.max_level}!")
            print(f"  Gravitational: d({args.max_level}) = {g3}")
            print(f"  Calogero-Moser: d({args.max_level}) = {c3}")
            print(f"  ==> The bracket algebra growth DOES distinguish "
                  f"integrability!")
            print(f"  ==> Paper methodology is VINDICATED.")
        else:
            # Check SVD gap difference
            g_gap = grav_svd_results.get(args.max_level, (0, [], 0))[2]
            c_gap = cm_svd_results.get(args.max_level, (0, [], 0))[2]
            gap_ratio = g_gap / c_gap if c_gap > 0 else float('inf')

            print(f"\n  Dimensions MATCH at level {args.max_level}: "
                  f"both = {g3}")
            print(f"  SVD gap ratio: Grav={g_gap:.2e}, CM={c_gap:.2e}, "
                  f"ratio={gap_ratio:.2f}")

            if abs(gap_ratio - 1.0) > 0.5:
                print(f"\n  SVD gaps DIFFER significantly!")
                print(f"  ==> The SVD gap structure may distinguish "
                      f"integrability.")
                print(f"  ==> Paper should focus on gap analysis, "
                      f"not just dimension.")
            else:
                print(f"\n  SVD gaps are similar.")
                print(f"  ==> Bracket algebra growth does NOT distinguish "
                      f"integrability from non-integrability.")
                print(f"  ==> Paper's non-integrability certificate claim "
                      f"needs revision.")
                print(f"  ==> Recommend reframing as 'algebraic complexity "
                      f"measure' rather than 'non-integrability certificate'.")

    print(f"\n  Total computation time: {time():.0f}s")


if __name__ == "__main__":
    main()
