"""Word-length-graded dimensions g_L of the Lie algebra generated by H12,H13,H23
(N=3, d=1, V=-g/r, generic masses), computed mod p with FLINT.
For 1/r the algebra is graded by word length (weights x:2, p:-1, u:-2), so
g_L = dim span{ [H_a1,[H_a2,...,H_aL]] }.
formal: u_ij free symbols (repo's convention).  physical: evaluated at u_ij = 1/(x_i-x_j)."""
import sys, random, time
from flint import nmod_mpoly_ctx, Ordering
P = 2147483647
ctx = nmod_mpoly_ctx.get(('x1','x2','x3','p1','p2','p3','u12','u13','u23'), modulus=P)
x1,x2,x3,p1,p2,p3,u12,u13,u23 = ctx.gens()
X=[x1,x2,x3]; Pm=[p1,p2,p3]; U={(0,1):u12,(0,2):u13,(1,2):u23}
IX={id(v):n for v,n in zip(ctx.gens(),ctx.names())}
NM=dict(zip([0,1,2],['x1','x2','x3'])); NP=['p1','p2','p3']; NU={(0,1):'u12',(0,2):'u13',(1,2):'u23'}
rng = random.Random(11)
m = [rng.randrange(2, P) for _ in range(3)]; g = [rng.randrange(2, P) for _ in range(3)]
inv2m = [pow(2*mi, -1, P) for mi in m]
T = [inv2m[i]*Pm[i]**2 for i in range(3)]
pairs = [(0,1),(0,2),(1,2)]
H = [T[i]+T[j]-g[k]*U[(i,j)] for k,(i,j) in enumerate(pairs)]
# chain rule: du_ij/dx_i = -(x_i-x_j) u^3 ; du_ij/dx_j = +(x_i-x_j) u^3
def Dx(f, k):
    out = f.derivative(NM[k])
    for (i,j),u in U.items():
        if k==i: out -= f.derivative(NU[(i,j)])*(X[i]-X[j])*u**3
        elif k==j: out += f.derivative(NU[(i,j)])*(X[i]-X[j])*u**3
    return out
def pb(f, h):
    return sum((Dx(f,k)*h.derivative(NP[k]) - f.derivative(NP[k])*Dx(h,k) for k in range(3)), ctx.from_dict({}))
class Basis:
    """incremental row echelon over GF(p) on sparse dict vectors"""
    def __init__(s): s.piv = {}; s.elems = []
    def add(s, vec, elem):
        v = dict(vec)
        while v:
            lead = max(v)
            if lead not in s.piv: break
            f = v[lead]; pv = s.piv[lead]
            for k,c in pv.items():
                nv = (v.get(k,0) - f*c) % P
                if nv: v[k] = nv
                else: v.pop(k, None)
        if not v: return False
        lead = max(v); inv = pow(v[lead], -1, P)
        s.piv[lead] = {k: c*inv % P for k,c in v.items()}; s.elems.append(elem); return True
def vec(f): return {tuple(k): int(c) for k,c in f.to_dict().items()}
NPTS = int(sys.argv[2]) if len(sys.argv)>2 else 400
ALLCH = len(sys.argv)>3 and sys.argv[3]=='all'
pts = []
for _ in range(NPTS):
    xs = [rng.randrange(P) for _ in range(3)]
    while len(set(xs))<3: xs = [rng.randrange(P) for _ in range(3)]
    ps = [rng.randrange(P) for _ in range(3)]
    sg = rng.choice([(1,1,1),(-1,1,1),(1,-1,-1),(1,1,-1),(-1,-1,1),(-1,-1,-1)]) if ALLCH else (1,1,1)
    us = [s*pow((xs[i]-xs[j]) % P, -1, P) % P for s,(i,j) in zip(sg,pairs)]
    pts.append(xs+ps+us)
def evalvec(f): return {i: int(f(*pt)) for i,pt in enumerate(pts) if int(f(*pt))}
maxL = int(sys.argv[1])
from flint import nmod_mat
def select_basis(cands):
    """Physical (evaluation) basis: pivot columns of rref of the S x n evaluation matrix."""
    M = nmod_mat([[int(c(*pt)) for c in cands] for pt in pts], P)
    R, rk = M.rref()
    piv = []; r = 0
    for j in range(len(cands)):
        if r < rk and int(R[r, j]) != 0:
            piv.append(j); r += 1
    return [cands[j] for j in piv], rk
layer = H
for L in range(1, maxL+1):
    t0 = time.time()
    cands = H if L == 1 else [pb(h, b) for b in layer for h in H]
    layer, rk = select_basis(cands)
    print(f"L={L:2d}  physical g_L={rk:6d}  ({len(cands)} cands, {time.time()-t0:.1f}s)" + ("  WARNING: rank hit sample count" if rk >= NPTS else ""), flush=True)
